### ISSUE TITLE
A way to detect a websocket server/wifi connection issue when using StreamProvider?

### ISSUE THREAD

**Issue by loicmas** [rrousselGit/river_pod#182] opened 2020-10-11 00:03 UTC
Hi Remi,

My flutter app consumes data from an in-house websocket (WS) server using a StreamProvider. I would like to implement an automatic reconnect in case the WS server or the wifi breaks. 

More precisely, what I am looking for to do is, when the WS server/wifi stops functioning properly, the UI should show the "loading UI" I scripted out (in my case a simple LinearProgressIndicator widget).

**What I achieved so far:**
I can capture the WS server/wifi failure in the below scenario:

1. I start my app but I turn the WS server/wifi OFF.
2. Five seconds later, I turn the WS server/wifi ON.
3. A few seconds later, my app loads the data properly on the screen.

To do so, I use the refresh functionality in the handleError() function as shown below:

```
final wsProvider =
    Provider.autoDispose.family<IOWebSocketChannel, String>((ref, ip) {
  // Open the connection
  return IOWebSocketChannel.connect('ws://$ip:$port/v1/path');
});

final hostProvider =
    StreamProvider.autoDispose.family<Host, String>((ref, ip) async* {
  final channel = ref.watch(wsProvider(ip));

  ref.onDispose(() {
    return channel.sink.close();
  });

  await for (final json in channel.stream.handleError((_) async {
    await Future.delayed(Duration(seconds: 5));
    ref.container.refresh(wsProvider(ip));
  })) {
    final jsonStr = jsonDecode(json as String);
    yield Host.fromJson(jsonStr as Map<String, dynamic>);
  }
});
```

**My issue:**
I am not able to capture the WS server/wifi failure in the following scenario:

1. I turn the WS server ON.
2. Then I start my app. At this point, it consumes the data properly and I can see them on the screen.
3. Five seconds later, I turn the WS server/wifi OFF.
4. The UI remains frozen on the last state and the app does not consume the data anymore (since the WS connection is broken). Instead of doing that, I would like the app to display to the "loading UI", waiting for the connection to be re-established.

**Remarks and question:**
I tried to use channel.stream.listen() instead of await(for final json in channel.stream) in hostProvider. But since it creates a StreamSubscription, I couldn't find a way to show the data on the screen.

Do you see a way to solve this issue using Riverpod?

I was thinking about implementing a provider that would listen to the socket connection independently to hostProvider and refresh the connection each time there is an error with it.

Thank you

**Comment by rrousselGit** [comment] 2020-10-12 09:46
At the moment, there is no way to make a `StreamProvider` reset to loading status

**Comment by rrousselGit** [comment] 2020-10-12 09:49
Duplicate of #121

**Closed by rrousselGit** 2020-10-12 09:49 UTC
Labels: question

**Comment by loicmas** [comment] 2020-10-12 13:24
Thank you for the reply and thanks for the package. It's awesome !! ;)

**Comment by KristianBalaj** [comment] 2020-10-19 21:02
Hey @loicmas here is a possible solution.

https://github.com/rrousselGit/river_pod/issues/121#issuecomment-712429076

**Comment by loicmas** [comment] 2020-10-20 20:42
Thanks, @KristianBalaj.

In the end, I found a workaround that works for my use case (probably not the most efficient though):

`
// My providers: channelProvider & streamProvider
static final channelProvider = Provider.autoDispose
    .family<IOWebSocketChannel, HttpParam>((ref, httpParam) {
  return IOWebSocketChannel.connect(
      'ws://${httpParam.ip}:$port/v1/${httpParam.path}');
});

static final streamProvider =
    StreamProvider.autoDispose.family<dynamic, HttpParam>((ref, httpParam) {
  final bStream =
      ref.watch(channelProvider(httpParam)).stream.asBroadcastStream();
      
  final sub = bStream.listen(
    (data) => null,
    onError: (_, stack) => null,
    onDone: () async {
      await Future.delayed(Duration(seconds: 10));
      ref.container.refresh(channelProvider(httpParam));
    },
  );

  ref.onDispose(() {
    print('-----------> HOSTS SOCKET CLOSES');
    return sub.cancel();
  });

  return bStream;
});

// I consume streamProvider that way in my widget:
return useProvider(MetricsWsRepository.streamProvider(HttpParam(
  ip: ip,
  path: 'hosts-ws',
))).when(
  data: (data) => doSomething1,
  loading:() => doSomething2,
  error: (_, stack) => doSomething3
  )
`
