### ISSUE TITLE
 Cannot read properties of null (reading 'getElement')

### ISSUE THREAD

**Issue by rebaz94** [rrousselGit/river_pod#980] opened 2021-12-01 11:23 UTC
Hi.
When using Riverpod on web it throws error that said ``` Cannot read properties of null (reading 'getElement')```
this happen only on debug mode

To Reproduce
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    const ProviderScope(
      child: TestApp(),
    ),
  );
}

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      overrides: [
        IntNotifier.provider.overrideWithValue(IntNotifier(0)),
      ],
      child: Scaffold(
        body: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(),
            const Menu(),
          ],
        ),
      ),
    );
  }
}

class Menu extends StatelessWidget {
  const Menu({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: const AnotherView(),
    );
  }
}

class AnotherView extends ConsumerWidget {
  const AnotherView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(IntNotifier.provider);
    return Center(
      child: Text(
        value.toString(),
        style: const TextStyle(
          fontSize: 35,
        ),
      ),
    );
  }
}

class IntNotifier extends StateNotifier<int> {
  IntNotifier(int state) : super(state);

  static final provider = StateNotifierProvider<IntNotifier, int>((_) => throw UnimplementedError());
}

```
error message is
```
The following JSNoSuchMethodError was thrown building AnotherView(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#6e662):
TypeError: Cannot read properties of null (reading 'getElement')

The relevant error-causing widget was: 
  AnotherView AnotherView:file:///Projects/Flutter/app/lib/repro.dart:51:20
When the exception was thrown, this was the stack: 
```

Dart and Riverpod version

Riverpod
```
version: ^1.0.0-dev.10
```

```
 Flutter (Channel master, 2.6.0-12.0.pre.868, on Mac OS X 10.15.4 19E287 darwin-x64, locale en)
    • Flutter version 2.6.0-12.0.pre.868 at /Users/rebo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fff85f9c57 (7 hours ago), 2021-11-30 23:09:05 -0500
    • Engine revision c2fcadef89
    • Dart version 2.16.0 (build 2.16.0-56.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rebo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7727

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E287 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

```

**Comment by lucavenir** [comment] 2021-12-03 11:09
Hi,

I didn't test your code yet, aren't you supposed to use a `StateNotifierProvider` to watch, override and generally use your `StateNotifier`?

In this example I can't see a single `Provider` being used, so I guess an error at some point is to be expected. Still, I guess Riverpod could give you more intel about why you're getting this error, so maybe this can be label as "enhancement"?

**Comment by rebaz94** [comment] 2021-12-03 11:22
Hi @lucavenir 

>I didn't test your code yet, but aren't you supposed to use a StateNotifierProvider to watch, override and generally use your StateNotifier?

Sorry I don't understand what you mean but the provider its been used in example above in ```AnotherView```
The problem is that it only crash on web and work in Desktop or Mobile.

Maybe related to this [#889](https://github.com/rrousselGit/river_pod/issues/889). but the issued is resolved in dart mixin and already merged to master. I don't know why this happen only on web

**Comment by rebaz94** [comment] 2021-12-03 11:24
@rrousselGit please can you check why this happen?
Thanks

**Comment by lucavenir** [comment] 2021-12-03 11:30
> the provider its been used in example above in `AnotherView`

You're actually using `IntNotifier.provider`, I can see that.

What I meant is: by reading the docs, I think you're supposed to define something like:
```dart
final intProvider = StateNotifierProvider<IntNotifier, int>(
    (ref) => IntNotifier(0),
);
```

And then in your `AnotherView`, instead of watching `IntNotifier.provider`, you'd directly watch `intProvider`.

I have no clue onto why your code works everywhere but in the web.

**Comment by rrousselGit** [comment] 2021-12-04 19:07
That's a very weird error.

What's failing is this internal line:

```dart
        final targetElement = reader.getElement();
```


where `reader` is null.

The thing is... `reader` is non-nullable. It being `null` shouldn't be possible. There's something really wrong here

**Comment by rrousselGit** [comment] 2021-12-04 19:37
This looks like a bug in the implementation of `map.putIfAbsent` on web.

I've found a workaround.
I'm trying to reproduce the problem outside of Riverpod and I'll raise an issue

**Comment by rebaz94** [comment] 2021-12-04 20:03
Oh again ```Map``` issue,  there is also another [bug](https://github.com/dart-lang/sdk/issues/47598) in ```VM Map``` but hopefully already fixed.

Thanks for your time fixing this problem

**Comment by rrousselGit** [comment] 2021-12-04 20:04
I found a reproduction if you want to have a laugh https://dartpad.dev/?null_safety=true&id=390dbf79cccb2934af50648dadc510b5&channel=beta

No idea why this bug happens **only** with Providers as map key. Other variables and non-web platforms work fine :shrug:

**Comment by rrousselGit** [comment] 2021-12-04 20:13
Closing in favor of https://github.com/dart-lang/sdk/issues/47852

**Closed by rrousselGit** 2021-12-04 20:13 UTC
Labels: bug, needs triage

**Comment by rrousselGit** [comment] 2021-12-05 00:40
I've deployed a new version with a fix

**Comment by rebaz94** [comment] 2021-12-05 07:41
Good work. thanks for your quick fix
