### ISSUE TITLE
[1.0.0-dev.6] wrong read when override

### ISSUE THREAD

**Issue by nikitadol** [rrousselGit/river_pod#686] opened 2021-08-16 04:15 UTC
**Describe the bug**
```log
======== Exception caught by widgets library =======================================================
The following ProviderException was thrown building _Home(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#117da):
An exception was thrown while building second:AutoDisposeProvider<int>#e15a2.

Thrown exception:
An exception was thrown while building first:AutoDisposeProvider<int>#bdd14.

Thrown exception:
Bad state: It shouldn't have happened

Stack trace:
#0      firstProvider.<anonymous closure> (package:bug/main.dart:7:12)
#1      AutoDisposeProvider.create (package:riverpod/src/provider/auto_dispose.dart:29:61)
```

**To Reproduce**

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() => runApp(ProviderScope(child: _Root()));

final firstProvider = Provider.autoDispose<int>(
  (ref) => throw StateError('It shouldn\'t have happened'),
  name: 'first',
);

final secondProvider = Provider.autoDispose<int>(
  (ref) => ref.watch(firstProvider),
  name: 'second',
);

class _Root extends ConsumerWidget {
  const _Root({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ProviderScope(
      overrides: [
        firstProvider.overrideWithValue(1),
      ],
      child: _Home(),
    );
  }
}

class _Home extends ConsumerWidget {
  const _Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    print(ref.watch(secondProvider));

    return Container();
  }
}
```

**Expected behavior**
I expected the second provider to read the value from the overridden provider

Perhaps this is not a bug, but it should be?

**Comment by davidmartos96** [comment] 2021-08-16 08:33
@nikitadol This is expected. You should override the second provider as well because it depends on the first. There are other issues and discussions about this situation.
You should change your code to:

```
overrides: [
    firstProvider.overrideWithValue(1),
    secondProvider,
],
```

**Comment by nikitadol** [comment] 2021-08-16 08:40
Hi @davidmartos96 

> This is expected

Is it described somewhere?

> There are other issues and discussions about this situation.

Could you show it?

**Comment by davidmartos96** [comment] 2021-08-16 08:44
@nikitadol Here is one: https://github.com/rrousselGit/river_pod/discussions/573
I know there is an issue out there, but can't find it.

I don't think it's described anywhere. I answered here to let you know. It was a bit confusing to me as well at first.

**Comment by nikitadol** [comment] 2021-08-16 08:45
@davidmartos96 
Thanks!

**Comment by wujek-srujek** [comment] 2021-08-16 10:09
@nikitadol @davidmartos96 Here you are: https://github.com/rrousselGit/river_pod/issues/575, https://github.com/rrousselGit/river_pod/issues/669

**Comment by wujek-srujek** [comment] 2021-08-16 10:30
BTW, I personally think this design decision is terrible, and more and more bugs will be created here (until it is documented, but even then not every one will read it). It's not maintainable to be forced to hunt down all dependent providers and override them as well, and then the ones that depend on them as well, etc.

**Comment by davidmartos96** [comment] 2021-08-16 10:56
@wujek-srujek As Remi pointed out it works like in regular provider, you need to override there as well. Maybe with Static metaprogramming is not as cumbersome.
Here is a diagram on how I see providers interacting.

Riverpod:
![IMG_2021-08-16-12-48-59-448.jpg](https://user-images.githubusercontent.com/22084723/129552923-010d5237-00b4-4bc7-a858-7cf48dfd9b87.jpg)

Equivalent in Provider:
![IMG_2021-08-16-12-49-08-075.jpg](https://user-images.githubusercontent.com/22084723/129552987-b946a070-b7be-46ec-aff4-8a591dc08be7.jpg)

As I see it, a provider in riverpod is like a reusable configuration on how to create a piece of state that it's stored in a ProviderContainer (ProviderScope).
Overriding a provider requires overriding the dependencies as well because they hold state relative to a different scope.
I'm sure this is a nontrivial problem.

**Comment by rrousselGit** [comment] 2021-08-17 07:28
> BTW, I personally think this design decision is terrible, and more and more bugs will be created here (until it is documented, but even then not every one will read it). It's not maintainable to be forced to hunt down all dependent providers and override them as well, and then the ones that depend on them as well, etc.

@wujek-srujek 

As I mentioned before, that's not a "decision". There is no other way.

I wish I could automatically override a provider, but this is not possible to implement.

The problem is, a provider can depend on new providers at any time (especially with Future/StreamProvider or StateNotifierProvider). Yet to be able to automatically overrride a provider, we need to know all the dependencies of a provider.


I have one improvement in mind, which is to allow users to define the list of dependencies:

```dart
final provider = ...

final scoped = Provider((ref) {
  ref.watch(provider);
}, dependencies: {provider});
```

in which case when overriding `provider`, I will be able to override `scoped` too.
But this is not implemented yet.

The goal is also to have this list be automatically generated once we have static-metaprogramming.

**Comment by rrousselGit** [comment] 2021-08-17 07:30
In any case, I will close this since this is expected.

**Closed by rrousselGit** 2021-08-17 07:30 UTC
Labels: bug, needs triage
