### ISSUE TITLE
Wrapping MyApp() in ProviderScope causes Chrome App to load endlessly 

### ISSUE THREAD

**Issue by Wizzel1** [rrousselGit/river_pod#955] opened 2021-11-25 20:49 UTC
**Describe the bug**
My App doesn't load in Chrome when I am wrapping my App in a ProviderScope()

**To Reproduce**
Create a WebApp with Flutter 2.5.3
Import hooks_riverpod
Wrap App in ProviderScope
Select Chrome as Device
Click Run and Debug

**Expected behavior**
I was expecting my app to load as before

**Comment by daniellampl** [comment] 2021-11-25 21:44
Related #889

**Comment by rrousselGit** [comment] 2021-11-27 12:12
Duplicate of #889

**Closed by rrousselGit** 2021-11-27 12:12 UTC
Labels: bug, needs triage
