### ISSUE TITLE
Operand warning with latest master

### ISSUE THREAD

**Issue by alarmatwork** [rrousselGit/river_pod#1192] opened 2022-02-15 08:02 UTC
**Describe the bug**
Marter channel in flutter Is introducing warning in logs like:
```
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_riverpod-1.0.3/lib/src/framework.dart:275:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==


/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:42:29: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/binding.dart').
    _state = WidgetsBinding.instance!.lifecycleState;
                            ^
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:43:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:52:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);

```

**To Reproduce**
in pubspec.yaml add following dependencies:

  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3

**Expected behavior**
Just annoying red warning
[✓] Flutter (Channel master, 2.11.0-0.0.pre.501, on macOS 12.2.1 21D62 darwin-arm, locale en-EE)

**Comment by rrousselGit** [comment] 2022-02-15 09:04
Closing as duplicate of https://github.com/rrousselGit/river_pod/issues/1156

**Closed by rrousselGit** 2022-02-15 09:04 UTC
Labels: bug, needs triage
