### ISSUE TITLE
ConsumerWidget and initState() ?

### ISSUE THREAD

**Issue by ericchuawc** [rrousselGit/river_pod#290] opened 2021-01-26 10:11 UTC
Hi all,

I am currently using StatefulWidget and inside my initState(), I have something like this to trigger getProgram() upon load the screen.

```
@override
  void initState() {
    super.initState();
    context.read(programStateNotifier).getProgram(widget.id);
  }

```

What if I want to use ConsumerWidget, how can I achieve similar effect? I can't find this override initState() for ConsumerWidget?

Any help? Thanks.

**Comment by rrousselGit** [comment] 2021-01-26 10:47
Make a StatefulWidget instead.

**Comment by ericchuawc** [comment] 2021-01-26 23:33
The reason I need to use initState in StatefulWidget due to this challenge.

I have a StateNotifier like this

```
ProgramListNotifier(
    this.read,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<List<Program>> programs,
  ]) : super(programs ?? AsyncValue.loading()) {
    getPrograms();
  }
```

This way seems to work without initState()

However my challenge is this

Say I have 2 screens

Screen 1: Program List
Screen 2: Program Details

When I tap on a Program e.g. ABC Learning Program, it will go into Screen 2 to show the details of this program. I need to pass in ID from Screen 1 to Screen 2.

In Screen 2 StateNotifier, I can't figure out how to get the ID from Screen 1.

```
ProgramDetailNotifier(
    this.read,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<Program> program,
  ]) : super(program ?? AsyncValue.loading()) {
    **getProgram(id); // how to pass id here?**
  }
```

Any help?

**Comment by feronetick** [comment] 2021-01-26 23:44
Please read this example. Is this what you need?

```dart
final favoritesProvider = FutureProvider((ref) {
  return watch(favoritesRepository).getFavorites();
});

final favoriteDetailsProvider = FutureProvider.family((ref, favoriteId) {
  return watch(favoritesRepository).getFavoriteDetails(favoriteId);
});

class FavoritesRootScreen extends ConsumerWidget {
  const FavoritesRootScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return Scaffold(
      appBar: AppBar(),
      body: watch(favoritesProvider).when(data: (favorites) {
        return ListView.builder(
          itemCount: favorites.length,
          itemBuilder: (context, index) {
            final favorite = favorites[index];

            return ListTile(
              title: Text(favorite.title),
              onTap: () => Navigator.push(context, MaterialPageRoute(
                builder: (context) {
                  return FavoriteDetailsScreen(favoriteId: favorite.id);
                },
              )),
            );
          },
        );
      }, loading: () {
        return CircularProgressIndicator();
      }, error: (error, stack) {
        return Text('$error\n$stack');
      }),
    );
  }
}

class FavoriteDetailsScreen extends ConsumerWidget {
  const FavoriteDetailsScreen({@required this.favoriteId, Key key})
      : assert(favoriteId != null),
        super(key: key);

  final int favoriteId;

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return Text(favoriteId.toString());
  }
}
```

**Comment by ericchuawc** [comment] 2021-01-27 00:09
Thanks for sharing.

The reason I didn't use FutureProvider, as I need to know the state (AsyncValue.loading, AsyncValue.Error, AsyncValue.data). 

Example,

```
final programListNotifierProvider = StateNotifierProvider<ProgramListNotifier>(
  (ref) {
    final ProgramService programService = ProgramService();
    final SharedPreferencesService sharedPreferenceService =
        ref.watch(sharedPreferencesServiceProvider);
    return ProgramListNotifier(ref.read, programService, sharedPreferenceService);
  },
);

class ProgramListNotifier extends StateNotifier<AsyncValue<List<Program>>> {
  final ProgramService _service;
  final SharedPreferencesService sharedPreferencesService;
  final Reader read;

  ProgramListNotifier(
    this.read,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<List<Program>> programs,
  ]) : super(programs ?? AsyncValue.loading()) {
    getPrograms();
  }

  Either<NetworkExceptions, List<Program>> _result;
  Either<NetworkExceptions, List<Program>> get result => _result;
  void _setResult(Either<NetworkExceptions, List<Program>> result) {
    _result = result;
  }

  Future<void> getPrograms() async {
    _getPrograms();
  }

  Future<void> retryLoading() async {
    state = const AsyncValue.loading();
    _getPrograms();
  }

  Future<void> refresh() async {
    _getPrograms();
  }

  Future<void> _getPrograms() async {
    final Token token = await sharedPreferencesService.getAccessToken();
    await Task(() => _service.getPrograms(token))
        .attempt()
        .mapLeftToFailure()
        .run()
        .then((value) => _setResult(value));
    result.fold(
      (failure) => {
        state = AsyncValue.error(NetworkExceptions.getErrorMessage(failure))
      },
      (programs) {
        state = AsyncValue.data(programs);
      },
    );
  }
}
```

Then in my ConsumerWidget, I can add the ProviderListener and monitor the onChange.

```
@override
  Widget build(BuildContext context, ScopedReader watch) {
    return Scaffold(
      body: ProviderListener(
        provider: programListNotifierProvider.state,
        onChange: (context, state) {
          if (state is AsyncError) {
            ErrorMessagePopup.show(context, state.error.toString()); // show snackbar
          }
        },
        child: ...,
      ),
    );
  }
```

So if I want to retain using StateNotifier, how can I pass in the ID to the 2nd Screen's StateNotifier?

```
ProgramDetailNotifier(
    this.read,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<Program> program,
  ]) : super(program ?? AsyncValue.loading()) {
    getProgram(id); // how to pass id here?
  }
```

Any help? Thanks.

**Comment by feronetick** [comment] 2021-01-27 00:18
> The reason I didn't use FutureProvider, as I need to know the state (AsyncValue.loading, AsyncValue.Error, AsyncValue.data).

FutureProvider just return AsyncValue. Not future. For future you should use `watch(myFutureProvider.future)`

Oookay. In your case you can pass ID of entity directly in StateNotifier constructor and provide it with .family provider:

```dart

final programDetailProvider = StateNotifierProvider.family((ref, id) {
  return ProgramDetailNotifier(
    id,
    ref.watch(serviceProvider),
    ref.watch(preferencesProvider),
  );
});

class ProgramDetailNotifier extends StateNotifier {
  ProgramDetailNotifier(
    this._id,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<Program> program,
  ]) : super(program ?? AsyncValue.loading()) {
    getProgram(_id); // how to pass id here?
  }
}

```

**Comment by ericchuawc** [comment] 2021-01-27 02:02
Oh I didn't know about family feature, I will give them a try soon. Thanks again @feronetick

**Comment by ericchuawc** [comment] 2021-01-27 07:46
For these 2 lines

```
    ref.watch(serviceProvider),
```

I presume it based on this right?

```
final serviceProvider = Provider<ProgramService>(
  (ref) {
    return ProgramService();
  },
);
```

So I don't have to manually define this below.

`final ProgramService programService = ProgramService();`

So what is the advantage of using ref.watch() vs the above code?

**Comment by feronetick** [comment] 2021-01-27 07:55
> I presume it based on this right?

Right.

> So I don't have to manually define this below.

Oh ok. Just inject service into notifier as you like. This is just an example.

**Comment by ericchuawc** [comment] 2021-01-27 08:18
I have changed accordingly to your examples.

```
final programProvider = StateNotifierProvider.family((ref, id) {
  return ProgramNotifier(
    id,
    ref.watch(programServiceProvider),
    ref.watch(sharedPreferencesServiceProvider),
  );
});

class ProgramNotifier extends StateNotifier<AsyncValue<List<Program>>> {
  final ProgramService _service;
  final SharedPreferencesService sharedPreferencesService;
  final String id;

  CourseChapterNotifier(
    this.id,
    this._service,
    this.sharedPreferencesService, [
    AsyncValue<List<Program>> programs,
  ]) : super(programs ?? AsyncValue.loading()) {
    getProgram(id);
  }
...

```
When I call from Flutter side

```
ProviderListener(provider: programProvider.state,

and

Consumer(builder: (context, watch, child) {
                final programs = watch(programProvider.state);
```

Got this error

`The getter 'state' isn't defined for the type 'StateNotifierProviderFamily<CourseChapterNotifier, dynamic>'.`

I have also tried this

```
final programProvider = StateNotifierProvider.family<ProgramNotifier, String>((ref, id) {
  return ProgramNotifier(
    id,
    ref.watch(programServiceProvider),
    ref.watch(sharedPreferencesServiceProvider),
  );
});
```

Same error too.

`The getter 'state' isn't defined for the type 'StateNotifierProviderFamily<CourseChapterNotifier, String>'.`

When I type courseChapterNotifierProvider. in my code editor, in the dropdown selection I can't find state too.

Any idea? Thanks.

**Comment by feronetick** [comment] 2021-01-27 08:21
You should pass programId to family provider

```dart
Consumer(
  builder: (context, watch, child) {
    final programs = watch(programProvider(programId).state); /// <<--- you should pass ID there
 //...
```

**Comment by fabiancrx** [comment] 2021-01-27 11:02
Hey @ericchuawc if the issue is solved could you close it?

**Closed** 2021-01-27 19:34 UTC
Labels: question

**Comment by camillo777** [comment] 2021-05-22 14:53
This entire post is so awesome it should be put as a real scenario example in the Riverpod docs!!!!

**Comment by cgestes** [comment] 2022-12-01 14:26
@pbouttier was exactly wondering how to do just that.

**Comment by pbouttier** [comment] 2022-12-01 14:48
@cgestes i found two solutions : 

1.  like Rémy in Marvel example, with a ProviderScope `overrideWith`
2.  with a .familly 

An override allows you to avoid passing the argument if you have sub widgets that need the info (by just calling ref.watch(...)),, but it's "less clean" from my point of view

**Comment by cgestes** [comment] 2022-12-01 16:15
@pbouttier thanks :)

1/ override works perfectly thanks! Wasn't obvious, it only override the default value to this is great!
2/ .familly feels like a hack. I just want an initial value. other components dont know about the familly and dont have to know about it.
