### ISSUE TITLE
ref.refresh doesn't work in a FutureProvider.autoDispose

### ISSUE THREAD

**Issue by NickBalnaves** [rrousselGit/river_pod#949] opened 2021-11-24 12:35 UTC
For the code below I would expect `someProvider` to produce a new random int when pressing the button as it is calling a provider which calls ref.refresh but the value of `someProvider` stays the same. When moving the contents of `refreshSomeProvider` inside the button onPressed method then it works as expected.

```dart
void main() {
  runApp(ProviderScope(child: MaterialApp(home: Home())));
}

final someProvider = FutureProvider.autoDispose<int>((final ref) async {
  await Future.delayed(const Duration(seconds: 2), () {});

  return Random().nextInt(1000000);
});

final refreshSomeProvider = FutureProvider.autoDispose<void>(
  (final ref) async {
    await Future.delayed(const Duration(seconds: 2), () {});

    ref.refresh(someProvider);
  },
);

class Home extends ConsumerWidget {
  @override
  Widget build(final BuildContext context, final WidgetRef ref) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SomeButton(),
          SomeText(),
        ],
      ),
    );
  }
}

class SomeButton extends ConsumerWidget {
  @override
  Widget build(final BuildContext context, final WidgetRef ref) => Center(
        child: ElevatedButton(
          onPressed: () async => await ref.watch(refreshSomeProvider.future),
          child: const Text('test'),
        ),
      );
}

class SomeText extends ConsumerWidget {
  @override
  Widget build(final BuildContext context, final WidgetRef ref) {
    final someProviderValue = ref.watch(someProvider).asData?.value ?? 0;

    return Text('someProvider: $someProviderValue');
  }
}

```

**Comment by rrousselGit** [comment] 2021-11-27 12:21
Duplicate of #875

**Closed by rrousselGit** 2021-11-27 12:21 UTC
Labels: bug, needs triage
