### ISSUE TITLE
Awaiting multiple StreamProviders and FutureProviders at the same time does not work

### ISSUE THREAD

**Issue by ablbol** [rrousselGit/river_pod#454] opened 2021-04-21 09:48 UTC
I have 2 StreamProviders and 1 FutureProvider like this.

userProvider will return firebase auth user (StreamProvider)
myProfile holds current user profile (StreamProvider)
mySettings holds current user settings (FutureProvider) 

I would like to await all three providers at once like the following:

```
final userDataProvider = FutureProvider.autoDispose<UserData>((ref) async {
  final user = await ref.watch(userProvider.last);
  final myProfile = await ref.watch(myProfileProvider.last);
  final mySettings = await ref.watch(mySettingsProvider.future);

  return Future.value(
    UserData(
      user: user,
      myProfile: myProfile,
      mySettings: mySettings,
    ),
  );
});
```

When I did that I ran into infinite loop.  The only way I can avoid the infinite loop is if I await on one StreamProvider (either userProvider OR myProfileProvider) and the FutureProvider (mySettings).  But If I await on two StreamProviders, the infinite loop comes back. So the following will work

```
final userDataProvider = FutureProvider.autoDispose<UserData>((ref) async {
  final asyncUser = ref.watch(userProvider);
  final myProfile = await ref.watch(myProfileProvider.last);
  final mySettings = await ref.watch(mySettingsProvider.future);


  if (asyncUser is AsyncError) {
    final error = asyncUser as AsyncError<User?>;
    return Future.error(error, error.stackTrace);
  }

  return Future.value(
    UserData(
      user: asyncUser.data?.value,
      myProfile: myProfile,
      mySettings: mySettings,
    ),
  );
});
```

But this is not what I want.  I would like to be able to await all 3 providers.  Does anybody know of a way to do that?

**Comment by rrousselGit** [comment] 2021-04-21 09:50
> When I did that I ran into infinite loop.

What does an infinite loop means here?

**Comment by ablbol** [comment] 2021-04-21 09:56
When I read userDataProvider like the following, then the console starts printing messages infinity.  It never stops unless I exit out of flutter.  In a normal case, few lines are printed to the console and that is it until some even happens.  In my case, I am running into infinite loop and tons of text is printed to the console non stop.

```
    return useProvider(userDataProvider).when(
      loading: () {
        return Container(
          color: Colors.white,
          child: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
      error: (error, stackTrace) {
        return Container(
          color: Colors.white,
          child: Center(child: Text(error.toString())),
        );
      },
      data: (userData) {
        if (userData.user == null) {
          return const WelcomeScreen();
        } else if (!userData.user!.emailVerified) {
          return const VerifyEmailScreen();
        } else if (userData.myProfile == null) {
          return const BeforeYouStartScreen();
        } else {
          return const HomeScreen();
        }
      },
    );
```

**Comment by rrousselGit** [comment] 2021-04-21 09:58
>  then the console starts printing messages infinity.

What message? I don't see any prints inside your example

**Comment by ablbol** [comment] 2021-04-21 10:00
The message that get printed infinitely come from flutter and from my code.  I wonder how I can show screen shot of the console to make it easier to understand!!

**Comment by rrousselGit** [comment] 2021-04-21 10:01
Consider writing a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by ablbol** [comment] 2021-04-21 10:45
Here is a basic example that mimics the example above.  Please look at the following code where I have userDataProvider.  In this provider I want to be able to await for 2 StreamProviders (userProvider & myProfileProvider) and 1 FutureProvider (mySttingsProvider).  if I await for all 3 together, I end up stuck inside the loading event.  On the other hand, If I only await on one StreamProvider (myProfileProvider) and one FutureProvider (mySettingsProvider), things will be ok.
I want to await all three providers to be safe but can't do that.

```
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

class UserData {
  String? user;
  String? myProfile;
  String? mySettings;

  UserData({
    required this.user,
    required this.myProfile,
    required this.mySettings,
  });
}

Stream<String> getUser() async* {
  await Future.delayed(Duration(seconds: 1));
  yield 'user';
}

Stream<String> getMyProfile() async* {
  await Future.delayed(Duration(seconds: 1));
  yield 'myprofile';
}

final userProvider = StreamProvider.autoDispose<String>((ref) {
  return getUser();
});

final myProfileProvider = StreamProvider.autoDispose<String>((ref) {
  return getMyProfile();
});

final mySettingsProvider = FutureProvider.autoDispose<String>((ref) async {
  await Future.delayed(Duration(seconds: 1));
  return Future.value('mySettings');
});

final userDataProvider = FutureProvider.autoDispose<UserData>((ref) async {
  // uncomment this line
  final user = await ref.watch(userProvider.last);
  // Or this line but not both
  // final user = ref.watch(userProvider).data!.value;
  final myProfile = await ref.watch(myProfileProvider.last);
  final mySettings = await ref.watch(mySettingsProvider.future);

  return UserData(
    user: user,
    myProfile: myProfile,
    mySettings: mySettings,
  );
});

class FirstScreen extends HookWidget {
  FirstScreen();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: useProvider(userDataProvider).when(
        loading: () {
          print('loading');
          return Center(child: CircularProgressIndicator());
        },
        error: (error, errorStack) => Center(child: Text(error.toString())),
        data: (data) {
          print(data);
          if (data.user == null) {
            return Container(color: Colors.yellow);
          } else if (data.myProfile == null) {
            return Container(color: Colors.red);
          } else {
            return Container(color: Colors.green);
          }
        },
      ),
    );
  }
}

```

**Comment by rrousselGit** [comment] 2021-04-21 11:31
Ah it looks like your streams keeps getting disposed

Try doing:

```dart
final user = ref.watch(userProvider.last);
final myProfile = ref.watch(myProfileProvider.last);
final mySettings = ref.watch(mySettingsProvider.future);

return UserData(
  user: await user,
  myProfile: await myProfile,
  mySettings: await mySettings,
);
```

**Comment by ablbol** [comment] 2021-04-21 11:46
Oh my GOD. It does work. Thanks so much for your help.  I will go ahead and close the issue.

**Comment by ablbol** [comment] 2021-04-22 16:52
There seams to be one issue withe the proposed solution above.  Whenever the StreamProviders or FutureProviders inside userDataProvider receive data, then userDataProvider will dispose and recreate again.  This is not a good behavior  because it will force other widgets to dispose and rebuild.  Is there anything to resolve this.
Thanks

**Comment by rrousselGit** [comment] 2021-04-22 17:22
That is what `ref.watch` is all about.

Why is that a problem? It is logical for `UserData` to be recreated when any of the values it depends on is updated

**Comment by ablbol** [comment] 2021-04-22 17:34
Suppose that userData depends on (N) StreamProviders, then when each stream provider updates, then userData provider will also update which makes the widgets underneath to start flickering.  especially when all stream providers resolve quickly.  Right now my screen widget under userData provider is flickering really bad.  After investigating this, I found out that userData gets disposed and recreated multiple times (3 times from 3 streams). 3 disposes + 3 creations.  I mean I don't have problem with userData provider getting disposed and recreated. I don't want my screens to dispose and rebuild. Also if the screens under userData provider has async calls, then those calls will start conflicting with the screen dispose.

**Comment by ablbol** [comment] 2021-04-22 17:38
If I make my code like the following, then my screens will not dispose and rebuild.

```
return useProvider(userProvider).when(
      loading: () {
        return Container(
          color: Colors.white,
          child: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
      error: (error, stackTrace) {
        return Container(
          color: Colors.white,
          child: Center(child: Text(error.toString())),
        );
      },
      data: (user) {
        return useProvider(myProfileAsyncProvider).when(
          loading: () {
            return Container(
              color: Colors.white,
              child: Center(
                child: CircularProgressIndicator(),
              ),
            );
          },
          error: (error, stackTrace) {
            return Container(
              color: Colors.white,
              child: Center(child: Text(error.toString())),
            );
          },
          data: (myProfile) {
            return useProvider(mySettingsProvider).when(
              loading: () {
                print('===> loading - InitialScreen:mySettingsProvider');
                return Container(
                  color: Colors.white,
                  child: Center(
                    child: CircularProgressIndicator(),
                  ),
                );
              },
              error: (error, stackTrace) {
                return Container(
                  color: Colors.white,
                  child: Center(child: Text(error.toString())),
                );
              },
              data: (mySettings) {
                if (user == null) {
                  return const WelcomeScreen();
                } else if (!user.emailVerified) {
                  return const VerifyEmailScreen();
                } else if (myProfile == null) {
                  return const BeforeYouStartScreen();
                } else {
                  return const HomeScreen();
                }
              },
            );
          },
        );
      },
    );
```

**Comment by ablbol** [comment] 2021-04-22 17:59
Here is a very basic example. Second Screen does not depend on any provider what so ever so you would expect that it should not rebuild.  But it does rebuild.

```
// code for first_screen.dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:test_app/screens/second_screen.dart';

class UserData {
  String? user;
  String? myProfile;
  String? mySettings;

  UserData({
    required this.user,
    required this.myProfile,
    required this.mySettings,
  });
}

Stream<String> getUser() {
  return Stream.periodic(Duration(seconds: 1), (u) => 'user-$u');
}

Stream<String> getMyProfile() async* {
  await Future.delayed(Duration(seconds: 1));
  yield 'myprofile';
}

final userProvider = StreamProvider.autoDispose<String>((ref) {
  return getUser();
});

final myProfileProvider = StreamProvider.autoDispose<String>((ref) {
  return getMyProfile();
});

final mySettingsProvider = FutureProvider.autoDispose<String>((ref) async {
  await Future.delayed(Duration(seconds: 1));
  return Future.value('mySettings');
});

final userDataProvider = FutureProvider.autoDispose<UserData>((ref) async {
  print('===> created - userDataProvider');
  final user = ref.watch(userProvider.last);
  final myProfile = ref.watch(myProfileProvider.last);
  final mySettings = ref.watch(mySettingsProvider.future);

  ref.onDispose(() => print('===> disposed - userDataProvider'));
  return UserData(
    user: await user,
    myProfile: await myProfile,
    mySettings: await mySettings,
  );
});

class FirstScreen extends HookWidget {
  const FirstScreen();

  @override
  Widget build(BuildContext context) {
    useEffect(() {
      print('===> created - FirstScreen');
      return () => print('===> disposed - FirstScreen');
    }, []);

    return Scaffold(
      body: useProvider(userDataProvider).when(
        data: (data) {
          print('data - $data');
          return const SecondScreen();
        },
        loading: () {
          print('loading');
          return Center(child: CircularProgressIndicator());
        },
        error: (error, stackTrace) => Center(child: Text(error.toString())),
      ),
    );
  }
}

```
And here is the code for the second screen.
```
// code for second screen
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class SecondScreen extends HookWidget {
  const SecondScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    useEffect(() {
      print('===> created - SecondScreen');
      return () => print('===> disposed - SecondScreen');
    }, []);

    return Text('I am screen 2');
  }
}

```

**Comment by rrousselGit** [comment] 2021-04-24 21:10
Could you include _all_ the code? Your example lacks a main and the other parts.

**Comment by ablbol** [comment] 2021-04-24 21:14
Here is the code in main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:test_app/screens/first_screen.dart';

void main() {
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: FirstScreen(),
    );
  }
}

```

**Comment by rrousselGit** [comment] 2021-04-24 21:38
It is normal that your `SecondScreen` gets disposed of.

This isn't because `userDataProvider` changed, but because your screen was removed temporarily (as userDataProvider re-entered loading state).

Since the widget was removed from the widget tree, it got disposed.

**Comment by ablbol** [comment] 2021-04-24 21:55
Ok, so what should I do to make sure that the second_screen does not get removed temporarily!!

**Comment by rrousselGit** [comment] 2021-06-27 13:08
I will close this since the original question was answered.

For your other issue, my recommendation would be to watch the providers that need to be kept alive in a widget.
If you have further questions, feel free to open a new issue

**Closed by rrousselGit** 2021-06-27 13:08 UTC
Labels: question
