### ISSUE TITLE
Avoid unnecessary rebuilds when using StateProvider

### ISSUE THREAD

**Issue by funwithflutter** [rrousselGit/river_pod#133] opened 2020-09-17 06:28 UTC
I'm familiar with how the normal Provider can be used to avoid unnecessary widget rebuilds, for example the below will only cause rebuilds when the actual length changes:
```dart
final uncompletedTodosCount = Provider((ref) {
  return ref
      .watch(todoListProvider.state)
      .where((todo) => !todo.completed)
      .length;
});
```
But, the same doesn't apply when using StateProvider on its own. Please see the example below:

```dart
// Will cause rebuilds when returning the same value
final _showPanel = StateProvider<bool>((ref) {
  return false;
});

// I do not expect this widget to rebuild when pressing the button, as the state is set to the same value.
class WillRebuild extends HookWidget {
  const WillRebuild({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final showPanel = useProvider(_showPanel);
    print('building, state: ${showPanel.state}');
    return RaisedButton(
      onPressed: () {
        showPanel.state = false; // setting to the same value
      },
      child: Text('Set'),
    );
  }
}

// Only causes a rebuild in listeners when the returned value changes
final _filteredShowPanel = Provider<bool>((ref) {
  final state = ref.watch(_showPanel).state;
  return state;
});

// Expected, doesn't rebuild unnecessarily
class WontRebuild extends HookWidget {
  const WontRebuild({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final showPanel = useProvider(_filteredShowPanel);
    print('building, state: $showPanel');
    return RaisedButton(
      onPressed: () {
        context.read(_showPanel).state = false; // setting to the same value
      },
      child: Text('Set'),
    );
  }
}
```

It would be nice if `StateProvider` only causes a rebuild when the actual state changes. For clarity, I also tried the below and it did not work:

```dart
// Not expected, as the state is the same
class WillRebuild extends HookWidget {
  const WillRebuild({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final showPanel = useProvider(_showPanel).state;
    print('building, state: $showPanel');
    return RaisedButton(
      onPressed: () {
        context.read(_showPanel).state = false; // setting to the same value
      },
      child: Text('Set'),
    );
  }
}
```

**Comment by rrousselGit** [comment] 2020-09-17 07:40
You could do:

```dart
if (context.read(_showPanel).state! = false) 
  context.read(_showPanel).state = false;  
```


StateProvider doesn't do it for performance reason. 99% of the time, the value is different. So making such == comparison is just wasted resources

**Comment by funwithflutter** [comment] 2020-09-17 07:58
Sure, I agree with that. And I know I can do my own check.

But I didn't expect this behaviour. Both from a Provider (what the docs suggest), and ValueNotifier perspective. The other providers do an equality check, and same with using normal ValueNotifier in combination with ValueListenableBuilder.

**Comment by rrousselGit** [comment] 2020-09-17 08:07
I'll think about it.
It would maybe make sense for StateProvider to compare the value. The value is almost always a primitive, so it's cheap to compare.

**Comment by rydmike** [comment] 2021-07-19 15:14
Agree with @funwithflutter, this would make it more consistent with expected behavior. Is it included in 1.0.0-dev releases?

**Comment by rrousselGit** [comment] 2021-10-02 00:19
Closing since `StateNotiifer` now filters values with `identical`, which should take care of the problem

**Closed by rrousselGit** 2021-10-02 00:19 UTC
Labels: enhancement

**Comment by josh-burton** [comment] 2022-05-05 04:05
@rrousselGit I'm facing an issue with using a freezed model in a StateNotifier. `identical` seems to return false on 2 freezed models that are equal (model1 == model2 is true).

Is that expected?

**Comment by rrousselGit** [comment] 2022-05-05 07:49
Yes it is.
