### ISSUE TITLE
Question: riverpod cli migrate failure

### ISSUE THREAD

**Issue by lcdsmao** [rrousselGit/river_pod#607] opened 2021-07-14 12:43 UTC
**Describe the bug**

When I running `riverpod migrate` (to 1.0.0) in our project, only the `pubspec.yaml` got updated.
Is there any way to debug the cli behavior?

Output:
```
[INFO] Setting up analysis contexts...
[INFO] done
searching...
[SEVERE] Suggestor.generatePatches() threw unexpectedly.
RangeError: Value not in range: -1
[INFO] Setting up analysis contexts...
[INFO] Setting up analysis contexts...
[INFO] done
[INFO] done
searching...
```

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by TimWhiting** [comment] 2021-07-14 16:28
I've made a fix so we can enable more debugging of this. Once the new migration tool gets published can you try again? Note that you need to reset the pubspec.yaml to use the old version of riverpod, run `flutter pub get` and make sure there are no analysis errors in your files.

**Comment by TimWhiting** [comment] 2021-07-14 21:12
Try using the latest migration tooling and supply the verbose flag -v

`pub global activate riverpod_cli 1.0.0-dev.5`
`riverpod migrate -v`

**Comment by lcdsmao** [comment] 2021-07-15 00:01
@TimWhiting 
Thanks for the quick response!
It seems the cli throws the error in our test file.
I can reproduce with this content:

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final testProvider = Provider((ref) => 0);

void main() {
  final container = ProviderContainer();
  final count = container.read(testProvider);
  expect(count, 0);
}

```

And the output:
```
[FINE] codemod: file: test/my/test_file.dart
[SEVERE] codemod: Suggestor.generatePatches() threw unexpectedly.
RangeError: Value not in range: -1
dart:core                                                    _StringBase.substring
package:riverpod_cli/src/migrate/unified_syntax.dart 409:16  RiverpodUnifiedSyntaxChangesMigrationSuggestor.updateProviderType
package:riverpod_cli/src/migrate/unified_syntax.dart 444:5   RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInstanceCreationExpression
package:analyzer/src/dart/ast/ast.dart 6125:15               InstanceCreationExpressionImpl.accept
package:analyzer/src/dart/ast/ast.dart 10523:19              VariableDeclarationImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 137:48                GeneralizingAstVisitor.visitAnnotatedNode
package:analyzer/dart/ast/visitor.dart 235:44                GeneralizingAstVisitor.visitDeclaration
package:analyzer/dart/ast/visitor.dart 595:7                 GeneralizingAstVisitor.visitVariableDeclaration
package:analyzer/src/dart/ast/ast.dart 10517:50              VariableDeclarationImpl.accept
package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
package:analyzer/src/dart/ast/ast.dart 10618:16              VariableDeclarationListImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 599:7                 GeneralizingAstVisitor.visitVariableDeclarationList
package:analyzer/src/dart/ast/ast.dart 10612:15              VariableDeclarationListImpl.accept
package:analyzer/src/dart/ast/ast.dart 10665:19              VariableDeclarationStatementImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 528:40                GeneralizingAstVisitor.visitStatement
package:analyzer/dart/ast/visitor.dart 603:7                 GeneralizingAstVisitor.visitVariableDeclarationStatement
package:analyzer/src/dart/ast/ast.dart 10661:15              VariableDeclarationStatementImpl.accept
package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
package:analyzer/src/dart/ast/ast.dart 1056:17               BlockImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 528:40                GeneralizingAstVisitor.visitStatement
package:analyzer/dart/ast/visitor.dart 165:32                GeneralizingAstVisitor.visitBlock
package:analyzer/src/dart/ast/ast.dart 1052:50               BlockImpl.accept
package:analyzer/src/dart/ast/ast.dart 1011:12               BlockFunctionBodyImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 330:46                GeneralizingAstVisitor.visitFunctionBody
package:analyzer/dart/ast/visitor.dart 168:56                GeneralizingAstVisitor.visitBlockFunctionBody
package:analyzer/src/dart/ast/ast.dart 1007:50               BlockFunctionBodyImpl.accept
package:analyzer/src/dart/ast/ast.dart 4950:11               FunctionExpressionImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 191:56                GeneralizingAstVisitor.visitCollectionElement
package:analyzer/dart/ast/visitor.dart 273:42                GeneralizingAstVisitor.visitExpression
package:analyzer/dart/ast/visitor.dart 341:58                GeneralizingAstVisitor.visitFunctionExpression
package:riverpod_cli/src/migrate/unified_syntax.dart 291:11  RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitFunctionExpression
package:analyzer/src/dart/ast/ast.dart 4944:50               FunctionExpressionImpl.accept
package:analyzer/src/dart/ast/ast.dart 4826:25               FunctionDeclarationImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 137:48                GeneralizingAstVisitor.visitAnnotatedNode
package:analyzer/dart/ast/visitor.dart 235:44                GeneralizingAstVisitor.visitDeclaration
package:analyzer/dart/ast/visitor.dart 205:7                 GeneralizingAstVisitor.visitCompilationUnitMember
package:analyzer/dart/ast/visitor.dart 440:7                 GeneralizingAstVisitor.visitNamedCompilationUnitMember
package:analyzer/dart/ast/visitor.dart 334:7                 GeneralizingAstVisitor.visitFunctionDeclaration
package:riverpod_cli/src/migrate/unified_syntax.dart 503:11  RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitFunctionDeclaration
package:analyzer/src/dart/ast/ast.dart 4819:50               FunctionDeclarationImpl.accept
package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
package:analyzer/src/dart/ast/ast.dart 2091:21               CompilationUnitImpl.visitChildren
package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
package:analyzer/dart/ast/visitor.dart 202:52                GeneralizingAstVisitor.visitCompilationUnit
package:analyzer/src/dart/ast/ast.dart 2084:50               CompilationUnitImpl.accept
package:codemod/src/ast_visiting_suggestor.dart 79:10        AstVisitingSuggestor.call
```

**Comment by TimWhiting** [comment] 2021-07-15 04:23
Yes, that was part of the issue. Problems with string matching 🤦. There were a few other issues though as well with ProviderContainer.

Fix is in a pull request now.

**Comment by lcdsmao** [comment] 2021-07-15 06:58
@TimWhiting 
Thanks for the fixing.
I tried #610 in our project and seems there are still some problems related to the `ProviderContainer`.

Here are some outputs:

1. Incorrect suggestion
```
[FINE] codemod: diff size: 45
[FINE] codemod: diff sizing:
        numRowsToPrint: 45
        sizeOfOld: 4
        sizeOfNew: 1
        sizeOfDiff: 5
        sizeOfContext: 40
        sizeOfUpContext: 20
        sizeOfDownContext: 20
        startContextLineNumber: -7
        endContextLineNumber: 37
[FINE] codemod: old text:
ProviderContainer(overrides: [
      getTopRegisterCampaignUseCaseProvider
          .overrideWithValue(getTopRegisterCampaignUseCase),
    ]).listen(topRegisterCampaignStateProvider.notifier).read
[FINE] codemod: new text:
ref.read
```

2. Server error
```
[SEVERE] codemod: Empty patch suggested: <SourcePatch: on /Users/mao/my/repo/packages/app/test/state/myfile.dart from 36:21 to 36:38>
```
And the code in L36:
```dart
        container = ProviderContainer(
```

**Comment by TimWhiting** [comment] 2021-07-15 13:28
Okay I'll look into it some more

**Comment by TimWhiting** [comment] 2021-07-15 14:35
@lcdsmao Can you try the most recent changes? The migration to v1.0.0 is pretty complex so thanks for being patient and working with me to find the edge cases I missed.

**Comment by lcdsmao** [comment] 2021-07-15 15:00
@TimWhiting 
Hi, I tried the latest #610.
And the error changed:

```
[FINE] codemod: file: test/foundation/betting_test.dart
[SEVERE] codemod: Empty patch suggested: <SourcePatch: on /Users/mao/git/wt-app-2/packages/app/test/my_test.dart from 5:3 to 5:20>
```

And the content is like this:
```dart
import 'package:app/my_file.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() {
  ProviderContainer().read(myProvider);
}
```

**Comment by TimWhiting** [comment] 2021-07-15 15:59
Just pushed some updates and tested manually, for whatever reason Empty patches don't cause problems in tests, and only when running the migration tool via command-line

**Comment by lcdsmao** [comment] 2021-07-16 00:02
@TimWhiting 
Seems the previous problem was solved!

But now I found a new edge case:
```
00:17 +2 -1: test/unified_syntax_test.dart: Unified Syntax Migration [E]

  RangeError: Value not in range: -1
  dart:core                                                    _StringBase.substring
  package:riverpod_cli/src/migrate/unified_syntax.dart 418:16  RiverpodUnifiedSyntaxChangesMigrationSuggestor.updateProviderTyp
e
  package:riverpod_cli/src/migrate/unified_syntax.dart 473:5   RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInvocationEx
pression
  package:analyzer/dart/ast/visitor.dart 433:7                 GeneralizingAstVisitor.visitMethodInvocation
  package:riverpod_cli/src/migrate/unified_syntax.dart 555:13  RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitMethodInvoca
tion
  package:analyzer/src/dart/ast/ast.dart 7156:50               MethodInvocationImpl.accept
  package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 6746:15               ListLiteralImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 191:56                GeneralizingAstVisitor.visitCollectionElement
  package:analyzer/dart/ast/visitor.dart 273:42                GeneralizingAstVisitor.visitExpression
  package:analyzer/dart/ast/visitor.dart 423:36                GeneralizingAstVisitor.visitLiteral
  package:analyzer/dart/ast/visitor.dart 577:46                GeneralizingAstVisitor.visitTypedLiteral
  package:analyzer/dart/ast/visitor.dart 421:44                GeneralizingAstVisitor.visitListLiteral
  package:analyzer/src/dart/ast/ast.dart 6741:50               ListLiteralImpl.accept
  package:analyzer/src/dart/ast/ast.dart 7353:17               NamedExpressionImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 191:56                GeneralizingAstVisitor.visitCollectionElement
  package:analyzer/dart/ast/visitor.dart 273:42                GeneralizingAstVisitor.visitExpression
  package:analyzer/dart/ast/visitor.dart 443:52                GeneralizingAstVisitor.visitNamedExpression
  package:analyzer/src/dart/ast/ast.dart 7348:50               NamedExpressionImpl.accept
  package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 381:16                ArgumentListImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 143:46                GeneralizingAstVisitor.visitArgumentList
  package:analyzer/src/dart/ast/ast.dart 377:50                ArgumentListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 6131:19               InstanceCreationExpressionImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 191:56                GeneralizingAstVisitor.visitCollectionElement
  package:analyzer/dart/ast/visitor.dart 273:42                GeneralizingAstVisitor.visitExpression
  package:analyzer/dart/ast/visitor.dart 387:7                 GeneralizingAstVisitor.visitInstanceCreationExpression
  package:riverpod_cli/src/migrate/unified_syntax.dart 462:11  RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInstanceCrea
tionExpression
  package:analyzer/src/dart/ast/ast.dart 6125:15               InstanceCreationExpressionImpl.accept
  package:analyzer/src/dart/ast/ast.dart 10523:19              VariableDeclarationImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 137:48                GeneralizingAstVisitor.visitAnnotatedNode
  package:analyzer/dart/ast/visitor.dart 235:44                GeneralizingAstVisitor.visitDeclaration
  package:analyzer/dart/ast/visitor.dart 595:7                 GeneralizingAstVisitor.visitVariableDeclaration
  package:analyzer/src/dart/ast/ast.dart 10517:50              VariableDeclarationImpl.accept
  package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 10618:16              VariableDeclarationListImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 599:7                 GeneralizingAstVisitor.visitVariableDeclarationList
  package:analyzer/src/dart/ast/ast.dart 10612:15              VariableDeclarationListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 9840:19               TopLevelVariableDeclarationImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 137:48                GeneralizingAstVisitor.visitAnnotatedNode
  package:analyzer/dart/ast/visitor.dart 235:44                GeneralizingAstVisitor.visitDeclaration
  package:analyzer/dart/ast/visitor.dart 205:7                 GeneralizingAstVisitor.visitCompilationUnitMember
  package:analyzer/dart/ast/visitor.dart 565:7                 GeneralizingAstVisitor.visitTopLevelVariableDeclaration
  package:analyzer/src/dart/ast/ast.dart 9835:15               TopLevelVariableDeclarationImpl.accept
  package:analyzer/src/dart/ast/ast.dart 7581:20               NodeListImpl.accept
  package:analyzer/src/dart/ast/ast.dart 2091:21               CompilationUnitImpl.visitChildren
  package:analyzer/dart/ast/visitor.dart 456:10                GeneralizingAstVisitor.visitNode
  package:analyzer/dart/ast/visitor.dart 202:52                GeneralizingAstVisitor.visitCompilationUnit
  package:analyzer/src/dart/ast/ast.dart 2084:50               CompilationUnitImpl.accept
  package:codemod/src/ast_visiting_suggestor.dart 79:10        AstVisitingSuggestor.call
```

And the content added to `packages/riverpod_cli/fixtures/unified_syntax/input/widgets.dart` is like:
```dart
final container = ProviderContainer(
  overrides: [
    testProvider.overrideWithProvider(Provider((ref) => 100)),
  ],
);
```


Beside, I noticed the migration seems always suggest adding generic parameter like:
```dart
  ProviderContainer(overrides: [
    stateNotifierProvider.overrideWithValue(CounterTest()),
              // here
  ]).listen<Counter>(stateNotifierProvider.notifier, (value) {}).read();
```
Maybe this was too verbose to me, can we have some options to skip this suggestion automatically?

**Comment by lcdsmao** [comment] 2021-07-16 00:10
By the way, is it possible catching the update error and skip that update? 
So we can still migrate the rest codes.

**Comment by TimWhiting** [comment] 2021-07-16 01:34
The generic parameter is always added in the listen case, otherwise the callback will be untyped (Typed as Object?), so I'd prefer to keep it that way.

The tool we are using to apply the migration patches does not currently support catching single patches and skipping single updates, and unfortunately all of the updates for v1.0.0 are in one patch generator currently. The interface is that it asks us to generate all patches at once for a single file, and then it asks the user to approve one by one. So you would lose all updates for v1.0.0 in the particular file that had an error, but again, that would involve a change in a library we depend on, so it'd likely take some time for that to happen. I'd like to refactor into smaller updates, but it would take quite a bit of work, especially since v1.0.0 has a ton of changes, and we'd still have the same problem, unless I can get a PR for the library we depend on to let the user choose to allow for exceptions. 

For now I'll see if I can catch errors in the methods themselves and see if that works. Hard to tell though, since the migration depends on various pieces of information that is gathered throughout the file. I've also gone back through the files and double checked any place I'm doing a non-null assertion to make sure all of my assumptions about non-null are correct. Let me know if there are more exceptions and I'll add in more try-catch blocks, but I didn't see many places where they would be needed or used.

**Comment by lcdsmao** [comment] 2021-07-16 05:17
>The generic parameter is always added in the listen case, otherwise the callback will be untyped (Typed as Object?), so I'd prefer to keep it that way.

That's right. I didn't notice that the callback will become untyped. 🤦‍♂️

We success migrated with the latest #610!
Thanks! 🎉

But there are still some minor bugs:
- `ProviderScope(...)` suggest to migrate to `ProviderScope<>(...)`
- Any property or class name that contains `Provider` got a suggestion.
  - Example: `  return CachedNetworkImageProvider<>(imageUrl, cacheManager: cacheManager);`
- `AutoDisposeProviderFamily` type provider got suggestion in usage (not very sure about this):
  - Example:
```dart 
final mySelector = Provider.autoDispose.family<MyModel, MyParam>(...)

// Got suggestion:
ref.watch(mySelector<KeirinPlayerMaxRecordModel>(param))
```

**Comment by davidmartos96** [comment] 2021-07-16 08:25
@TimWhiting I've also encountered an issue when a project holds references of `context.read` from the `provider` package. Maybe it would be possible to match by library on top of matching the string?

**Comment by TimWhiting** [comment] 2021-07-16 13:16
I'll look into it. I'll probably have to match exact strings then, unless I can figure out the package like you said.

**Comment by TimWhiting** [comment] 2021-07-16 19:22
If either of you still have projects that need migrating or would be willing to revert to a prior commit temporarily and test out the new changes that would be really helpful.

**Comment by lcdsmao** [comment] 2021-07-17 00:36
Hi @TimWhiting 
I tried again and here are the results.

- property name contains `Provider` got suggestion
```diff
// files generated by protobuf
-  static final $core.Map<$core.int, VideoProvider> _byValue = $pb.ProtobufEnum.initByValue(values);
+  static final $core.Map<$core.int, VideoProvider> _byValue = $pb.ProtobufEnum.initByValue<>(values);

-  $0.VideoProvider get digestVideoProvider => $_getN(4);
+  $0.VideoProvider get digestVideoProvider => $_getN<>(4);
```

- `context.read` doesn't get suggestion
```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';

ImageProvider cachedOnlineImageProvider({
  required BuildContext context,
  required String imageUrl,
}) {
  // In the last try, `BuildContext context` was suggested to change to `Widget ref`
  final cacheManager = context.read(imageCacheManagerProvider);
  return CachedNetworkImageProvider(imageUrl, cacheManager: cacheManager);
}

```

- Family provider override does not get a suggestion
```dart
// nothing change
      myProvider.overrideWithProvider((ref, param) => state),
```

- HookBuilder does not get a suggestion (seems more difficult...)
```dart
Widget _build(Widget child) => HookBuilder(
      builder: (_) {
        final foo = ref.watch(fooProvider);
 
        return  Center(
              child: child,
        );
      },
    );
```

- ScopedProvider lambda dost not get a suggestion
```dart
final myScopedProvider =
    Provider<Foo>(
  (watch) {
    // expect suggest ref.watch
    final bar = watch(barProvider);
    return Foo(bar);
  }
```

**Comment by TimWhiting** [comment] 2021-07-17 01:27
1: I'm pretty sure I have a fix for this

2: What is the type of imageCacheManagerProvider?

3: Not attempting to migrate family overrides right now

4. HookBuilder should be migrated, but I can't reproduce the problem

5. This doesn't look like a scoped provider or anything valid in riverpod ^0.14.0

**Comment by lcdsmao** [comment] 2021-07-17 01:34
> 2: What is the type of imageCacheManagerProvider?

```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';

final imageCacheManagerProvider = Provider<BaseCacheManager>((_) {
  return DefaultCacheManager();
});
```

> 4. HookBuilder should be migrated, but I can't reproduce the problem

I will try to create a reproducible example

> 5. This doesn't look like a scoped provider or anything valid in riverpod ^0.14.0

Sorry for not clarifying this. The suggestion change is like this:

```diff
final myScopedProvider =
-    ScopedProvider<Foo>(
+    Provider<Foo>(
  (watch) {
    // expect suggest ref.watch
    final bar = watch(barProvider);
    return Foo(bar);
  }
```

**Comment by lcdsmao** [comment] 2021-07-17 01:37
Anyway, I think the CLI currently works well enough. 😀
Thanks!

**Comment by TimWhiting** [comment] 2021-07-17 01:45
ScopedProvider fix now in as well. Glad it works well enough. Yeah, I still can't reproduce 2 & 4, and not planning on fixing 3, unless there is a lot of people wanting it.

**Comment by lcdsmao** [comment] 2021-07-18 01:39
>4. HookBuilder should be migrated, but I can't reproduce the problem

0.14:
```dart
Widget funWidget() {
  return Card(
    child: HookBuilder(builder: (context) {
      final v = useProvider(testProvider);
      return Text('$v');
    }),
  );
}
```

cli:
```dart
Widget funWidget(WidgetRef ref) {
  return Card(
    child: HookBuilder(builder: (context) {
      final v = ref.watch(testProvider);
      return Text('$v');
    }),
  );
}
```

my exception:
```dart
Widget funWidget() {
  return Card(
    child: HookConsumer(builder: (context, ref, child) {
      final v = ref.watch(testProvider);
      return Text('$v');
    }),
  );
}
```

I think it depends on the project and the CLI suggestion has no problem, so maybe we should skip this. 😅

**Comment by lcdsmao** [comment] 2021-07-18 01:49
About 2.

Input:
```dart
void showSnackOfCurrentProviderValue(BuildContext context) {
  final v = context.read(testProvider);
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(content: Text('$v')),
  );
}
```

My expectation output:
```dart
void showSnackOfCurrentProviderValue(BuildContext context, WidgetRef ref) {
  final v = ref.read(testProvider);
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(content: Text('$v')),
  );
}
```

Is it possible?

**Closed** 2021-07-25 13:55 UTC
Labels: bug
