### ISSUE TITLE
Keeping data based on some strategies.

### ISSUE THREAD

**Issue by YeungKC** [rrousselGit/river_pod#745] opened 2021-09-14 09:51 UTC
I'm always frustrate when I want keep some provider, I want to keep some data based on some strategies (such as LRU or according to time, or permanent), this is very practical in some common data.

```dart

final dataProvider =
    FutureProvider.autoDispose.family<String, String>((ref, params) async {
  ref.onDispose(() {
    print('$params data onDispose');
  });
  await Future.delayed(Duration(seconds: 5));
  return params;
});

@hwidget
Widget home() {
  var context = useContext();
  return Scaffold(
    body: Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: ['foo', 'bar']
            .map(
              (e) => ElevatedButton(
                onPressed: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (BuildContext context) => Foo(e)));
                },
                child: Text(e),
              ),
            )
            .toList(),
      ),
    ),
  );
}

@hwidget
Widget foo(String name) {
  AsyncValue<String> data = useProvider(dataProvider(name));

  return Scaffold(
    appBar: AppBar(),
    body: data.when(
      data: (data) => Text(data),
      loading: () => const CircularProgressIndicator(),
      error: (_, __) => Text('error'),
    ),
  );
}

```

like this demo, some future is so expensive, I want keep some data based on LRU.

**Comment by rrousselGit** [comment] 2021-09-14 10:26
Could you expand on what the problem is here?

**Comment by YeungKC** [comment] 2021-09-14 10:40
Like this demo, when click Column.buttons, route will push a new page, and I click back, dataProvider will be destroyed, and I want keep data based on some strategies.

If I can do it, some page don't need load data, just use previous data.

**Comment by rrousselGit** [comment] 2021-09-14 11:14
>  route will push a new page, and I click back, dataProvider will be destroyed,

That shouldn't be the case, unless you used `pushReplacement`

**Comment by YeungKC** [comment] 2021-09-14 11:35
```dart

final dataProvider =
    FutureProvider.autoDispose.family<String, String>((ref, params) async {
  print('params: $params start load data');

  ref.onDispose(() {
    print('params: $params data onDispose');
  });
  await Future.delayed(Duration(seconds: 5));

  print('params: $params loaded data');
  return params;
});

@hwidget
Widget home() {
  var context = useContext();
  return Scaffold(
    body: Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: ['foo', 'bar']
            .map(
              (e) => ElevatedButton(
                onPressed: () {
                  print('click $e, push params $e');
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (BuildContext context) => Foo(e)));
                },
                child: Text(e),
              ),
            )
            .toList(),
      ),
    ),
  );
}

@hwidget
Widget foo(String name) {
  final context = useContext();
  final data = useProvider(dataProvider(name));

  return Scaffold(
    appBar: AppBar(
      leading: BackButton(onPressed: () {
        print('params: $name, pop');
        Navigator.maybePop(context);
      }),
    ),
    body: data.when(
      data: (data) => Text(data),
      loading: () => const CircularProgressIndicator(),
      error: (_, __) => Text('error'),
    ),
  );
}


```


```

flutter: click foo, push params foo
flutter: params: foo start load data
flutter: params: foo loaded data
flutter: params: foo, pop
flutter: params: foo data onDispose
flutter: click foo, push params foo
flutter: params: foo start load data
flutter: params: foo loaded data

```

I think we may have misunderstood and I've added some logs that might help you understand what I mean.

We can see the logs:

-  I clicked foo button
- waited for data loaded
- then click back. Now, because dataProvider don't have any listener, so it will be destroyed.
- then click foo button again, the data need reload.

This behavior is expected, but sometimes I don’t want to reload, May want to keep five minutes?  if still don’t have listener, it should destroy.

**Comment by nwparker** [comment] 2021-09-14 23:56
I'm not an expert here, but would this solve your issues?
https://riverpod.dev/docs/concepts/modifiers/auto_dispose/#refmaintainstate

**Comment by YeungKC** [comment] 2021-09-15 03:09
Somewhat similar, but I may not want to preserve it forever, just for a period of time, or for a max total of preserved.

**Comment by rrousselGit** [comment] 2021-10-01 23:43
Closing in favour of https://github.com/rrousselGit/river_pod/issues/779

**Closed by rrousselGit** 2021-10-01 23:43 UTC
Labels: enhancement, question
