### ISSUE TITLE
flutter_riverpod 1.0.0 prevents app from running in Chrome in debug mode

### ISSUE THREAD

**Issue by daniellampl** [rrousselGit/river_pod#889] opened 2021-11-05 20:12 UTC
**Describe the bug**
When I change the version of `flutter_riverpod` from `1.0.0-dev.11` to `1.0.0`, the application is not able to run in debug mode using Chrome anymore. Changing it back to the previously used version results in starting the application as expected. I tried this with 3 different projects and also created a new project for testing purposes. Neither of them started correctly in Chrome.

There is no problem in release mode.

Running it in verbose mode shows that it gets stuck while injecting debugging metadata: 

![Bildschirmfoto 2021-11-05 um 21 08 58](https://user-images.githubusercontent.com/39054525/140572347-5972a69c-929f-4c61-bd5e-3125d5ba9880.png)

**To Reproduce**

Update `flutter_riverpod` to version `1.0.0` and run:

`flutter run -d chrome --verbose`

**Expected behavior**
It starts without any problem in Chrome.

**Comment by ymdhrk** [comment] 2021-11-05 20:40
This happens to me as well.

**Comment by xal** [comment] 2021-11-05 21:14
Not used riverpod before. Today tried 1.0.0 and app stuck on page loading with next error in chrome 
```
Uncaught TypeError: framework.OverrideWithProviderMixin$ is not a function
    at auto_dispose.dart:29
    at Object.makeGenericType [as AutoDisposeStateProvider$] (classes.dart:242)
    at load__packages__riverpod__src__state_provider_dart (auto_dispose.dart:29)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

Error occurs even without using overrideWithProvider. Just with simple ProviderScope wrapper

```
 runApp(ProviderScope(
      child: const MyApp(),
    ));
```

**Comment by rrousselGit** [comment] 2021-11-05 23:08
There's not much I can do about it, it's a bug in Dart

**Comment by cthurston** [comment] 2021-11-06 00:08
We are stuck at version dev.7. Anything after that we can't seem to get working in web.

**Comment by oussaid1** [comment] 2021-11-07 12:09
This happens to me as well. chrome keeps loading without showing anything ....

**Comment by Patrick386** [comment] 2021-11-07 14:33
Same problem after flutter and package upgrade.

[✓] Flutter (Channel master, 2.6.0-12.0.pre.624, on Mac OS X 10.15.7 19H1519 darwin-x64, locale ko-KR)
    • Flutter version 2.6.0-12.0.pre.624 at /Users/patrick386/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b0b21ecb5 (6 hours ago), 2021-11-07 01:37:35 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/patrick386/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1519 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.


![스크린샷 2021-11-07 오후 11 26 29](https://user-images.githubusercontent.com/49754877/140649287-2c3ac96a-5ce4-4639-9340-3b6960d3f7bf.png)

**Comment by TimWhiting** [comment] 2021-11-07 14:45
I'm going to lock this issue from comments, because this is a dart problem not a riverpod issue. Please upvote the linked dart-sdk issue.

**Comment by TimWhiting** [comment] 2021-11-17 01:17
For anyone following this issue, flutter master contains the fix from the dart-sdk & I've verified it works. We will have to see if the fix will be cherry-picked into other channels or not. Personally, I have frequently used flutter's master and dev channels without issue. If that worries you , you can always develop on other platforms on a more stable channel and then switch to the master channel to test out web specific pieces of your app. Additionally, note that this issue only applies to debug mode so you can always build web apps from other channels without issue.

**Comment by oussaid1** [comment] 2021-11-19 23:47
f

**Comment by oussaid1** [comment] 2021-11-19 23:48
tried it doesn't work , 
fingers crossed for the fix ...

**Comment by EndoNrak** [comment] 2021-11-21 13:08
I faced this issue with flutter stable channel .
As TimWhiting said (https://github.com/rrousselGit/river_pod/issues/889#issuecomment-971018136), this issue was resolved with flutter master channel. thx

**Comment by flyby3d** [comment] 2021-11-27 14:10
The issue is resolved also with flutter beta channel. tested today with Flutter 2.8.0-3.2.pre

**Comment by wilpar** [comment] 2021-12-01 15:45
confirmed. back in business with channel beta.  Thanks!  I thought I f'd something up, but no, not me this time.

**Comment by rrousselGit** [comment] 2021-12-04 20:02
I'll close this as it was fixed. It's only a matter of time before it reaches stable

**Closed by rrousselGit** 2021-12-04 20:02 UTC
Labels: bug, question

**Comment by timobaehrNexplore** [comment] 2021-12-09 08:05
@rrousselGit Flutter 2.8 is out as well as Dart 2.15. So bug is no longer relevant for stable.

**Comment by gurupatel107** [comment] 2021-12-11 13:52
Finally working fine in stable channel 2.8.0.
