### ISSUE TITLE
Initialize StateNotifierProvider Asynchronously

### ISSUE THREAD

**Issue by campanagerald** [rrousselGit/river_pod#127] opened 2020-09-16 11:58 UTC
How can I initialize StateNotifierProvider asynchronously? I want to initialize a list of before creating an instance of it. The data are coming from an api. The problem is the StateNotifierProvider doesn't work in async. Here below is my code: 

```
final countryListProvider = StateNotifierProvider((ref) async {
  try {
    final countryList = await ref.watch(countryRepository).getAllCountries();
    return CountryList(countryList);
  } catch (e) {
    print(e) // also how can i show the error in the UI
  }
});

class CountryList extends StateNotifier<List<CountryEntity>> {
   CountryList([List<Todo> initialCountryList]): super(initialCountryList ?? []);
  
   filterCountries(String str) async {
     try {
       final regex = RegExp(str, caseSensitive: false);
       return state
            .where((element) => regex.hasMatch(element.name))
            .toList();
    } catch(e) {
      rethrow;
    }
   } 
}
```

**Comment by rrousselGit** [comment] 2020-09-16 13:07
Are you looking for https://github.com/rrousselGit/river_pod/issues/57?

**Comment by campanagerald** [comment] 2020-09-16 13:16
Hi, thanks for this new state management solution. I think I don't need a a FutureProvider because I will not listen to it. I will only use country list data to show as a suggestion to my country text field.

**Comment by rrousselGit** [comment] 2020-09-16 18:30
I was referring to https://github.com/rrousselGit/river_pod/issues/57#issuecomment-663048181

**Comment by campanagerald** [comment] 2020-09-16 22:43
oh i see. if i do that where should initialize it? inside init state? Another thing. What does guard do? Is there a documentation for AsyncValue on how to use it? Thanks!

**Comment by rrousselGit** [comment] 2020-09-16 22:54
No need for initState. The StateNotifierProvider is enough

For AsyncValue, see its dartdoc https://pub.dev/documentation/riverpod/latest/all/AsyncValue-class.html

**Comment by campanagerald** [comment] 2020-09-17 02:28
Alright. thank you so much! I am gonna close this issue.

**Comment by campanagerald** [comment] 2020-09-17 03:53
Additional. Can you provide a use case for each Providers in the https://riverpod.dev/? I am overwhelmed because of many Providers. hehehe!

**Comment by rrousselGit** [comment] 2020-09-17 07:41
Each provider has its own documentation on pub https://pub.dev/documentation/riverpod/latest/all/FutureProvider-class.html

I'll search for a way to make this more accessible

**Comment by campanagerald** [comment] 2020-09-17 08:09
Thanks Thanks!

**Comment by rrousselGit** [comment] 2021-11-27 14:48
Closing as duplicate of #57

**Closed by rrousselGit** 2021-11-27 14:48 UTC
Labels: documentation
