### ISSUE TITLE
Sub-tree ProviderScope for local state provider?

### ISSUE THREAD

**Issue by sabetAI** [rrousselGit/river_pod#376] opened 2021-03-19 16:51 UTC
Suppose I have several instances of a `Page` widget, each with a Scaffold that has its own `AppBar`. I want to toggle something in the `AppBar` with a button in the `BottomNavBar`, without affecting the other pages. This is trivial with the `provider` package but impossible with `riverpod` (unless I'm mistaken), because providers have to be declared globally. I can't use the `provider` library for this specific functionality because its namespace clashes with `riverpod`. 

Are there any simple solutions? Perhaps placing a [`ProviderScope`](https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ProviderScope-class.html) at the root of the sub-tree might address this?

**Comment by sabetAI** [comment] 2021-03-19 19:25
I tried something like this

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final isOnProvider = ScopedProvider<IsOn>((ref) => null);

class IsOn {
  bool state = false;
}

void main() => runApp(ProviderScope(child: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Page(),
    );
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      overrides: [isOnProvider.overrideWithValue(IsOn())],
      child: Scaffold(
        appBar: AppBar(
          title: Consumer(
            builder: (context, watch, child) {
              bool state = watch(isOnProvider).state;
              if (state) {
                return Text('On');
              } else {
                return Text('Off');
              }
            },
          ),
        ),
        bottomNavigationBar: BottomNavigationBar(
          items: [
            BottomNavigationBarItem(
                icon: IconButton(
                  onPressed: () => context.read(isOnProvider).state ^= true,
                  icon: Icon(Icons.ac_unit),
                ),
                label: 'A'),
            BottomNavigationBarItem(icon: Icon(Icons.ac_unit), label: 'A'),
            BottomNavigationBarItem(icon: Icon(Icons.ac_unit), label: 'A')
          ],
        ),
      ),
    );
  }
}
```

but get 
```
The getter 'state' was called on null.
Receiver: null
Tried calling: state
```

It appears `context.read` for `onPressed` doesn't have access to the value in the `ProviderScope` above the `Scaffold` for some reason?

**Comment by rrousselGit** [comment] 2021-03-20 18:34
Riverpod voluntarily dissociate itself for "scoping" providers, because it is a source of problems.

Instead you should use [family](https://riverpod.dev/docs/concepts/modifiers/family)

**Comment by tbm98** [comment] 2021-03-31 16:01
maybe error caused by context.
try wrap `scaffold` by Builder

**Comment by rrousselGit** [comment] 2021-04-24 21:08
@tbm98 is correct, looking back at it this is a context issue

So I'll close this since this was answered

**Closed by rrousselGit** 2021-04-24 21:08 UTC
Labels: question

**Comment by gazialankus** [comment] 2021-09-07 07:51
> Riverpod voluntarily dissociate itself for "scoping" providers, because it is a source of problems.
> 
> Instead you should use [family](https://riverpod.dev/docs/concepts/modifiers/family)

However, ProviderScope with overrides helps create a different scope for a subtree. 
May help others that google it and land here https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ProviderScope-class.html

**Comment by derolf** [comment] 2022-04-02 09:51
Assume you override a Provider X in a subtree and you have a Provider Y that depends on X.

Will Y depend on X at root or overridden X in the subtree?

**Comment by rrousselGit** [comment] 2022-04-02 10:30
Y will depend on the override, not the root – assuming that you specified `dependencies`. Otherwise you'll get an exception

Riverpod prevents cases where Y would depend on the root X, since that's basically never the expected behavior.

**Comment by derolf** [comment] 2023-01-17 18:20
> Riverpod voluntarily dissociate itself for "scoping" providers, because it is a source of problems.
> 
> Instead you should use [family](https://riverpod.dev/docs/concepts/modifiers/family)

Do you have a nice example that uses `family` for maintaining local state inside of a Widget?

**Comment by derolf** [comment] 2023-01-18 12:08
So, I am now just using the `BuildContext` of the enclosing `Widget` as `key` in a family-provider.
