### ISSUE TITLE
Limit modifier

### ISSUE THREAD

**Issue by pstromberg98** [rrousselGit/river_pod#466] opened 2021-05-03 19:51 UTC
**Is your feature request related to a problem? Please describe.**
One of the default and primary features with Riverpod is the ability to "cache" state for the lifetime of the application (or when dependencies change). The `autoDispose` is there for cases in which you don't want to cache indefinitely, like when using `family` with a constantly changing parameter that isn't ever reused (to avoid a memory leak). But what if you have a constantly changing parameter, have values that may be reused, and want to avoid a possible massive memory footprint?

**Describe the solution you'd like**
A limit modifier on family providers that would limit how many providers under that family can exist at once. This would allow developers to tweak the memory footprint of family providers to their liking. The use could be really simple and would only require an integer to define the instance limit `final exampleProvider = Provider.family.limit(4, (ref, param) => param));`.

**Describe alternatives you've considered**
This could definitely be done by the developer themselves but would most likely meaning giving up the use of a family provider and creating a specialized state notifier to do the work of destroying data when hitting a given limit. The syntax above is obviously much simpler and easier for the developer.

**Additional context**
One problem I do see with this is the possibility of family providers in use that exceed the given limit. But I think the limit would only apply to "detached" providers. I can provide some concrete examples that would benefit from this if needed. Thanks! 🙌

**Comment by ldasilva-net** [comment] 2021-05-03 22:49
Maybe this can be related with #142 enhancement request. I think in essence we want something similar.

**Comment by rrousselGit** [comment] 2021-05-04 10:47
Limiting how many instances of a family are in memory doesn't make sense because of the reactive nature of the framework.  

I'd suggest using `autoDispose` and keep watching the nodes that you want to keep alive in a widget


The API could likely be improve by having a getter instead of a boolean for `maintainState`. But I need to gather use-cases on what those edge-cases are. Do you mind sharing yours?

**Comment by pstromberg98** [comment] 2021-05-04 14:30
@rrousselGit I'm not sure about that actually. It is not limiting *all* instances of a family but would be limiting the *unused* instances. For example if the limit is 5, you could have any number of family instances in use but only up to 5 that are unused, thus "cached" or "kept alive". I don't see how that would conflict with the reactive nature of the framework, but maybe I am not catching what you are catching?

I can't provide too many screenshots for privacy reasons but imagine a page that displays data based off of a selected date. You would have a date picker like below
![Screen Shot 2021-05-04 at 8 18 39 AM](https://user-images.githubusercontent.com/18646900/117017990-575f8a00-acb1-11eb-98c0-aa305a89c7b9.png)

Users can scroll forward and backward in time without limit. The data is asynchronously loaded so I am using a FutureProvider family. The parameter for the family is a string that represents a year, month, and day (ex: '2020-04-04') which the associated data would be loaded from. Now a user could definitely load a lot of info while navigating days and the info provided from the FutureProvider isn't a small amount of data. I would use autoDispose but I want the most recently viewed days to instantly show up instead of reload the data. The user would most likely look at 4-5 days in the week so in this case I would set the limit to 4-5 days. Though as I am typing this out I think @ldasilva-net may be right in that his enhancement request would help with this. If I was able to clear all family providers then I wouldn't need the limit modifier at least in this case.

**Comment by rrousselGit** [comment] 2021-05-04 14:59
>  It is not limiting all instances of a family but would be limiting the unused instances.

yes but the problem is, how do we know which unused instance should be kept and which one should be GCed?
I could see people asking for a priority logic, which starts to get painfully complex.

+ the "limit" implies a magic number. Why limit to 5, why not 10 or 2?

>  I would use autoDispose but I want the most recently viewed days to instantly show up instead of reload the data.

Your scrollview could keep watching the recently visible items.
With a ListView, that could be done easily by increasing the `cacheExtent` property.


As for a feature request, for such use-case, it most likely makes more sense to use a timer instead
Like "dispose of the state only if it hasn't been used for x seconds".

**Comment by ldasilva-net** [comment] 2021-05-04 15:11
I think that all approaches end in the need to have a manual way of disposing providers and family providers. Something similar to [this](https://github.com/rrousselGit/river_pod/issues/142#issuecomment-694956069) but I think maybe is better with the `ProviderReference` instead of the `context`.
At what point in the application to do this is simply a decision of the developer.

**Comment by pstromberg98** [comment] 2021-05-04 15:22
> yes but the problem is, how do we know which unused instance should be kept and which one should be GCed?
I could see people asking for a priority logic, which starts to get painfully complex.

I was thinking it would be FIFO by default but sure I could see it become complex as well. But I also think there would be ways to handle the complexity.

> the "limit" implies a magic number. Why limit to 5, why not 10 or 2?

This is true but it wouldn't always a magic number. In the use case I gave, it is driven by the what the user is likely to do. I will admit though that it is a bit arbitrary so I think I mostly agree with you here.

> Your scrollview could keep watching the recently visible items.
With a ListView, that could be done easily by increasing the cacheExtent property.

The "day scroller" is a PageView where each page is represents a week. Either way I think depending on specific widget behavior because the state management library can't handle specific state needs is a crutch and not a long term solution. It also limits the cases to where you use ListView or ScrollView.

> As for a feature request, for such use-case, it most likely makes more sense to use a timer instead
Like "dispose of the state only if it hasn't been used for x seconds".

Personally I would find that behavior strange as a user and would expect data to be cached regardless of elapsed time. In fact I would expect data to be cached as long as I am using the feature which is another reason why I like the idea of disposing the family providers when needed.

In my opinion having the ability to dispose family providers is the best solution in terms of how many use cases it can apply to and the simplicity of it.

**Comment by rrousselGit** [comment] 2021-10-02 00:17
I'll close this in favour of https://github.com/rrousselGit/river_pod/issues/779 which should give more control over how providers are disposed.

**Closed by rrousselGit** 2021-10-02 00:17 UTC
Labels: enhancement
