### ISSUE TITLE
Allow to dispose maintainState Providers

### ISSUE THREAD

**Issue by ldasilva-net** [rrousselGit/river_pod#142] opened 2020-09-18 15:17 UTC
**Is your feature request related to a problem? Please describe.**
`maintainState` is a very nice feature for example for list pagination. But the problem is that maybe in one Flow we have 3 different screens withs lists, and then the user go to other Flow and continue using the app and never go back to this lists. So we have on memory different Providers states (a lot really, especially if we use Provider.family with "page" as param like Marvel example list) that we didn't need.

**Describe the solution you'd like**
I think on two solutions. 

1. An autodispose timer for `maintainState` Providers. Like 
```dart
final characterPages = FutureProvider.autoDispose.family<MarvelListCharactersReponse, CharacterPagination>(
  (ref, meta) async {
    final cancelToken = CancelToken();
    ref.onDispose(cancelToken.cancel);

    final repository = ref.read(repositoryProvider);
    final charactersResponse = await repository.fetchCharacters(
      offset: meta.page * kCharactersPageLimit,
      limit: kCharactersPageLimit,
      nameStartsWith: meta.name,
      cancelToken: cancelToken,
    );

    ref.maintainStateUntil(Duration(seconds: 60); // for not use two different properties assignment
    return charactersResponse;
  },
);
```

2. A way for manual dispose named Providers/family Providers.

```dart
final characterPages = FutureProvider.autoDispose.family<MarvelListCharactersReponse, CharacterPagination>(
  (ref, meta) async {
    final cancelToken = CancelToken();
    ref.onDispose(cancelToken.cancel);

    final repository = ref.read(repositoryProvider);
    final charactersResponse = await repository.fetchCharacters(
      offset: meta.page * kCharactersPageLimit,
      limit: kCharactersPageLimit,
      nameStartsWith: meta.name,
      cancelToken: cancelToken,
    );

    ref.maintainState = true;
    return charactersResponse;
  }, name: 'marvelCharacters'
);

ProviderContainer container = ProviderScope.containerOf(context);
container.disposeStatesFromNamed("marvelCharacters") //this dispose all states associated to this family provider
```

**Comment by tbm98** [comment] 2020-09-18 15:45
I think add a way to set duration is a good idea :D

**Comment by rrousselGit** [comment] 2020-09-18 16:09
In the example you've described, chances that a timer likely wouldn't work.

If the ListView is still in the widget tree (and chances are it is, as routes that are not visible are still mounted), the state would be preserved anyway even without `maintainState = true`

**Comment by rrousselGit** [comment] 2020-09-18 16:11
> container.disposeStatesFromNamed("marvelCharacters") //this dispose all states associated to this family provider

What about:

```dart
final family = Provider.family(...);
final provider = Provider(...);

context.disposeFamily(family);
context.disposeProvider(provder);
```

**Comment by ldasilva-net** [comment] 2020-09-18 16:26
> In the example you've described, chances that a timer likely wouldn't work.
> 
> If the ListView is still in the widget tree (and chances are it is, as routes that are not visible are still mounted), the state would be preserved anyway even without `maintainState = true`

Well, I'm using SliverList with the `ProviderScope` "override" approach (like the Marvel Grid example). So when I scroll down and go back, if I not maintein the state, I lose it. I still agree that "Duration" is not complete ideal in this scenario.







> > container.disposeStatesFromNamed("marvelCharacters") //this dispose all states associated to this family provider
> 
> What about:
> 
> ```dart
> final family = Provider.family(...);
> final provider = Provider(...);
> 
> context.disposeFamily(family);
> context.disposeProvider(provder);
> ```

Totally! Even better.

**Comment by rrousselGit** [comment] 2020-09-18 16:30
> Well, I'm using SliverList with the ProviderScope "override" approach (like the Marvel Grid example). So when I scroll down and go back, if I not maintein the state, I lose it. I still agree that "Duration" is not complete ideal in this scenario.

Indeed. But the currently visible item wouldn't be disposed

**Comment by ldasilva-net** [comment] 2020-09-18 17:00
> > Well, I'm using SliverList with the ProviderScope "override" approach (like the Marvel Grid example). So when I scroll down and go back, if I not maintein the state, I lose it. I still agree that "Duration" is not complete ideal in this scenario.
> 
> Indeed. But the currently visible item wouldn't be disposed

Sure. With `maintainState` I can guarantee a correct UX when I'm on the SliverList screen doing down/up gestures. I really need maintain the states here, then when I leave the screen the only important states to maintein are the used on the visible items until the screen was removed from Navigation stack.
I supose with your solution I can do something like:
```dart
useEffect(() {
    ...
    return () {
      context.disposeFamily(characterPages);
    };
  });
```

On the List screen `HookWidget`. With this I can maintain all the states for the family for don't lose the UX effect and avoid unnecessary server requests. The `disposeFamily` feature is important to if I need pull to request, because maybe one thing change and I need refresh the data.

**Comment by rrousselGit** [comment] 2020-09-18 17:17
> I supose with your solution I can do something like:
>
> ```dart
> useEffect(() {
>    ...
>    return () {
>      context.disposeFamily(characterPages);
>    };
>  });
> ```

Sadly no, it's more complex.
We don't want to dispose the provider when the widget is disposed. The issue is that the widget isn't disposed, so this would have no impact.

What you want is likely something on Navigator's level instead.
Such that the `maintainStateFor(Duration)` you are suggesting would be implemented for Navigator routes.
Then, when routes that are no-longer visible are destroyed, this would automatically dispose the providers.

But the `maintainStateFor(Duration)` for providers may be interesting for ListViews, to not keep items that haven't been viewed for a while alive.
Although tbh, this could be moved to the Widget layer too.

Rather than using `maintainState = true`, you may want to not use the flag at all, and instead increase the `ListView.cacheExtent` variable:

```dart
ListView(
    cacheExtent: 500?,
)
```

This would keep items that are not visible but close to being visible still alive. So if the user scrolls very far, items are disposed of. But if the item barely left the screen, its state is preserved.

**Comment by rrousselGit** [comment] 2020-09-18 17:20
> The disposeFamily feature is important to if I need pull to request, because maybe one thing change and I need refresh the data.

For refreshing a group of providers, there's an easy solution: create a dummy provider that all providers of this group listen to with `ref.watch`


```dart
final group = Provider<void>((ref) {});

final a = Provider((ref) {
  ref.watch(group);
  print('create A');
});

final B = Provider((ref) {
  ref.watch(group);
  print('create B');
});

....

context.refresh(group); // Will cause `a` and `b` to refresh
```

**Comment by ldasilva-net** [comment] 2020-09-18 21:15
> Sadly no, it's more complex.
> We don't want to dispose the provider when the widget is disposed. The issue is that the widget isn't disposed, so this would have no impact.
> 
> What you want is likely something on Navigator's level instead, such that the `maintainStateFor(Duration)` you are suggesting would be implemented for Navigator routes.
> Then, when routes that are no-longer visible are destroyed, this would automatically dispose the providers.
> 
> But the `maintainStateFor(Duration)` for providers may be interesting for ListViews, to not keep items that haven't been viewed for a while alive.
> Although tbh, this could be moved to the Widget layer too.

You are right. Needs to be worked at the navigation layer.
I think the two "ideas" (`maintainStateFor` and `context.disposeFamily / Provider`) are not mutually exclusive and give us more versatility for manage with more criterias Providers State lifes: On the one hand is desider a duration (or other criteria) for allow `maintainState` autodispose himself (I never really like the idea for `maintainState' never expire) and on the other give us more control to ensure at some point in the app some Providers/Family States were disposed.

> Rather than using `maintainState = true`, you may want to not use the flag at all, and instead increase the `ListView.cacheExtent` variable:
> 
> ```dart
> ListView(
>     cacheExtent: 500?,
> )
> ```
> 
> This would keep items that are not visible but close to being visible still alive. So if the user scrolls very far, items are disposed of. But if the item barely left the screen, its state is preserved.

I test it but the behiever it's not what I expect (for the last thing you comment and for making the user fetch/render much more data/widget than he needs).

**Comment by ldasilva-net** [comment] 2020-09-18 21:17
> > The disposeFamily feature is important to if I need pull to request, because maybe one thing change and I need refresh the data.
> 
> For refreshing a group of providers, there's an easy solution: create a dummy provider that all providers of this group listen to with `ref.watch`
> 
> ```dart
> final group = Provider<void>((ref) {});
> 
> final a = Provider((ref) {
>   ref.watch(group);
>   print('create A');
> });
> 
> final B = Provider((ref) {
>   ref.watch(group);
>   print('create B');
> });
> 
> ....
> 
> context.refresh(group); // Will cause `a` and `b` to refresh
> ```

But if Providers "a" and "b" are using `maintainState = true`, this works?

**Comment by dgaedcke** [comment] 2021-01-12 17:36
If I understand what Remi has written, maintainState ONLY applies to AFTER the Provider is no longer being listened to.  It does not change the rules on WHEN the provider would normally rebuild.
So yes, this should work even when  maintainState = true

**Comment by rrousselGit** [comment] 2022-02-27 15:04
> I still don't understand what "autoDispose" is actually disposing when maintainState = true

If the first line of your provider is `maintainState = true` and you never set it back to false, then yeah, `autoDispose` is not doing anything.


But it shouldn't be **always** true.
The point of `maintainState` is that it's conditional and can change over time.
You can call `maintainState = false` at any time, or delay the `maintainState = true` after an await.

**Comment by rrousselGit** [comment] 2022-02-27 15:05
In any case, the 2.0 offers a bunch of new life-cycles and high level configs which should offer more freedom over when providers are disposed.

So I'll close this

**Closed by rrousselGit** 2022-02-27 15:05 UTC
Labels: enhancement
