### ISSUE TITLE
Error: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/river_pod#954] opened 2021-11-25 15:35 UTC
I want to change the count as well when I get the data with the filter.

 flutter_riverpod: ^1.0.0

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on Mac OS X 10.15.7 19H1519 darwin-x64, locale ko-KR)
    • Flutter version 2.6.0-12.0.pre.826 at /Users/patrick386/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c1455a23a (2 days ago), 2021-11-23 21:13:05 -0500
    • Engine revision 539239e256
    • Dart version 2.16.0 (build 2.16.0-42.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/patrick386/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1519 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.

```

![스크린샷 2021-11-26 오전 12 18 21](https://user-images.githubusercontent.com/49754877/143467505-231483fc-73cc-487e-a8aa-f94b51d6ae6f.png)

**Comment by daniellampl** [comment] 2021-11-25 17:29
The problem is that you call `ctr.getFilterData()` during the build of the Widget. The `state = state.copyWith(count: products.length)` causes the `ref.watch(productNotifierProvider)` to rebuild the widget during build. So never ever call `setState` or any other mechanisms that cause the widget to rebuild during the build.

A simple solution would be a separate `Provider` that returns the products depending on the `selectedItemCategory`. And if you want to fetch the products via an API or something like that, change it to a `FutureProvider`.

**Comment by rrousselGit** [comment] 2021-11-27 12:15
As Daniel mentioned, you shouldn't call `getFilterData` within `build`. 
Chances are that you want to have this method be a getter on your Model class instead

In any case, I'll close this as it isn't a bug in Riverpod

**Closed by rrousselGit** 2021-11-27 12:15 UTC
Labels: bug, needs triage

**Comment by Patrick386** [comment] 2021-11-27 12:19
thank you. I solved the problem.
