### ISSUE TITLE
Inconsistent behavior of an auto-disposed StateProvider

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/river_pod#683] opened 2021-08-13 13:41 UTC
**Describe the bug**

Use case: one page in the application sets some data in a provider and navigates to another part of the app, which expects the state to be available. When the user leaves the other part of the app (by popping the routes), the state should be destroyed automatically as it is no longer needed.

In code below:
`intProvider` is an auto-disposing `StateProvider`. In `PageA`, when a button is clicked, the state is set to a value and the app navigates to `PageB`. `PageB` reads the value from `intProvider`.

There are two ways of setting the state that both compile and work similarly in many (all?) other respects, but differ in this use case:

1. `ref.read(intProvider).state = 17;` - With this code, `intProvider` is first created, then the state is set, then it is immediately disposed, and when its state is read in `PageB` after navigation, the provider state is created again and the initial value is returned. (Unexpected behavior.)
2. `ref.read(intProvider.notifier).state = 17;` - With this code, `intProvider` is created, then its state is set, and when its state is read in `PageB` after navigation, the value set in `PageA` (17) is returned. (Expected behavior).

(Similarly, reading also works with both `ref.read(intProvider).state` and `ref.read(intProvider.notifier).state`, and in this case there is seemingly no difference at all.

Related to the discussion started here: https://github.com/rrousselGit/river_pod/discussions/663.

Questions:
1. Why do both lines compile and allow pretty much the same things (read the state, set the state) but behave differently as far as disposing is concerned? (One is disposed immediately, the other not.)
2. Which one is actually the correct way to implement the use case?
3. If both lines are correct, what is actually the difference? Is there any documentation about it?

If `intProvider` were a `StateNotifierProvider` instead there would be no issue because `state` would be inaccessible and it would be necessary to call a custom method like `ref.read(intNotifierProvider.notifier).putState(17)` or similar, thus forcing option 2. This makes me thing option 2. is the right way. However, examples from https://pub.dev/documentation/riverpod/latest/riverpod/StateProvider-class.html access the `state` property like in option 1. Consider me mightily confused.

Note that making the provider non-auto-disposed is not a valid workaround because the state should be discarded when navigating back.

**To Reproduce**

You can observe both behaviors using the code below - just switch the lines in the button handler.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        home: PageA(),
      ),
    );
  }
}

class PageA extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            ref.read(intProvider).state = 17;
            // ref.read(intProvider.notifier).state = 17;

            Navigator.of(context).push<void>(
              MaterialPageRoute(
                builder: (context) => PageB(),
              ),
            );
          },
          child: Text('Click me'),
        ),
      ),
    );
  }
}

class PageB extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final val = ref.watch(intProvider).state;

    return Scaffold(
      body: Center(
        child: Text('Got: $val, expecting: 17'),
      ),
    );
  }
}

final intProvider = StateProvider.autoDispose<int>(
  (ref) {
    ref.onDispose(() {
      print('disposing');
    });

    print('creating');
    return 0;
  },
);
```

**Expected behavior**

I expect the state to always be available in `PageB` and the provider should not be disposed too soon.

I expect the API to make it hard to make mistakes, which isn't the case now as both lines compile and seemingly do the same thing, with the mentioned caveat. If one is incorrect, ideally it shouldn't be possible for it to compile at all.

**Comment by rrousselGit** [comment] 2021-08-13 13:57
There's a lot going on there. Let's break things down a bit

`ref.read(StateProvider)` vs `ref.read(StateNotifier.notifier)` are the same thing. The `.notifier` property matters only for `ref.watch`

The fact that when going from A to B using `ref.read(provider.notifier)` does _not_ dispose the state is weird edge-case. This isn't "expected" per say.

What happens is, by using `ref.read(provider.notifier)` instead of `ref.read(provider)`,  your provider took a bit longer to dispose (because Riverpod has to dispose `provider.notifier` before disposing `provider`).  
So by the time it was about to dispose the provider, the page B was already mounted.

You could see the that there's no difference if you did:

```dart
onPressed: () async {
  ref.read(...);

  await Future.delayed(Duration(seconds: 1));

  Navigator.push(...)
}
```

with this. whether you're using `ref.read(provider)` or `ref.read(provider.notifier)`, both cases would dispose the state.

**Comment by rrousselGit** [comment] 2021-08-13 14:00
As a matter of fact, the expected behaviour is that both syntax dispose the state before B is reached.
The fact that `ref.read(provider.notifier)` does't is more of a bug, which I will fix.


If you want to pass state to B, but destroy the state when B is popped, you need to mount B _before_ updating your provider.

**Comment by wujek-srujek** [comment] 2021-08-13 14:05
> As a matter of fact, the expected behaviour is that both syntax dispose the state before B is reached.
> The fact that `ref.read(provider.notifier)` does't is more of a bug, which I will fix.

Great, so now my app will be broken ;)

> If you want to pass state to B, but destroy the state when B is popped, you need to mount B _before_ updating your provider.

What does this mean? How would I 'mount' B?
One thing that works is to use `watch` instead of `read` in the tap callback, but I think this is also wrong?

**Comment by rrousselGit** [comment] 2021-08-13 14:12
You could do:

```dart
SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
  ref.read(intProvider).state = 17;
});

Navigator.of(context).push<void>(
  MaterialPageRoute(
    builder: (context) => PageB(),
  ),
);
```

This way, the state is modified in the same frame that mounts B, which will not cause the state to be disposed before B is visible.

**Comment by rrousselGit** [comment] 2021-08-13 14:13
Ideally I would recommend using `watch` inside `A` if possible. But you want the state to be destroyed when B is popped, so this is not the solution.

That's a fancy use-case though.

**Comment by wujek-srujek** [comment] 2021-08-13 14:23
The trick with `addPostFrameCallback` works, but the issue is now that PageB builds twice, the first time with the default value, which I don't want.

1. How about the other questions: why is it possible to write the same using 2 slightly different syntaxes? Is one not supposed to be used?
2. Is it Ok to use `watch` in a callback?
2. If it's a fancy use case, how would you otherwise implement it? Give information to another route (possibly deeply nested, so passing the arguments explicitly may not be attractive), and have it disposed when the routes are popped?

**Comment by rrousselGit** [comment] 2021-08-13 14:29
> How about the other questions: why is it possible to write the same using 2 slightly different syntaxes? Is one not supposed to be used?

.notifier exists for `ref.watch`. It changes how often the widget rebuilds.

Using it with .read has does nothing special. We could prevent using `ref.read(provider.notifier)` in favour of the other syntax, but honestly that's a phenomenal amount of work for something not very valuable.

That's more a use-case for linter

> Is it Ok to use watch in a callback?

Not in the callback, no. Instead use it within the build method.

> If it's a fancy use case, how would you otherwise implement it? Give information to another route (possibly deeply nested, so passing the arguments explicitly may not be attractive), and have it disposed when the routes are popped?


I personally don't understand the desire for using autoDispose here. I need more informations to give a correct answer.

**Comment by wujek-srujek** [comment] 2021-08-13 14:39
So basically I have an app which has different 'modes' - each mode prepares data of the same kind, but differently, puts it into a `StateProvider`, and then another part of the app (let's call it PartB) uses this data to do something with it (it behaves differently based on what the data actually is). Once PartB is popped, I want the data to be discarded so the user can do start over. Note that PartB is not just one page (in this case I would just push the new route with the data) - instead, it is many nested routes with many widgets, many of which need some part of the data to display to the user.

Of course, when PartB is popped, I can reset the provider manually, but I don't want to as I would have to do it in all of the 'modes' (each mode is a different page). With auto-dispose, this just works (until your fix breaks this, hehe).

**Comment by rrousselGit** [comment] 2021-08-13 14:43
What about using a scoped-provider or a different named route?

```dart
Navigator.of(context).push<void>(
  MaterialPageRoute(
    builder: (context) => ProviderScope(overrides: [mode.overrideWithValue(Mode.b)], child: PageB()),
  ),
);
```

**Comment by wujek-srujek** [comment] 2021-08-13 14:49
I tried this but `overrideWithValue` has its own issues that prevented me from using it: https://github.com/rrousselGit/river_pod/issues/575 - the provider that then reads the data in PartB doesn't get the overridden value.

**Comment by rrousselGit** [comment] 2021-08-13 14:52
Right, but it's either that, using autoDispose with the workaround mentioned previously, or manually resetting the state

**Comment by wujek-srujek** [comment] 2021-08-13 15:28
> .notifier exists for `ref.watch`. It changes how often the widget rebuilds.

@rrousselGit Could you elaborate on this? What is the difference between `ref.watch(provider.notifier).state` and `ref.watch(provider).state`? As both compile just fine. What do you mean by 'changes how often the widget rebuilds', is there any docs on this?

**Comment by rrousselGit** [comment] 2021-08-13 15:53
Using .notifier will not cause the widget to rebuild when the state changes.

This is similar to ChangeNotifierProvider.notifier and StateNotifierProvider.notifier.

**Comment by wujek-srujek** [comment] 2021-08-13 16:14
Wow, this is completely new to me. Is this documented somewhere?

**Comment by rrousselGit** [comment] 2021-08-13 16:17
The dartdoc of every ".notifier" explains it briefly

**Comment by wujek-srujek** [comment] 2021-08-13 17:32
Ah, right. I got confused because `StateProvider` is using `StateNotifierProvider` under the hood and it overrides `state` to be public, so I can get the state either by watching the provider or the notifier. For other types of notifiers there is no such confusion.

**Comment by rrousselGit** [comment] 2021-08-19 21:27
Looks like the difference between read(provider) and read(provider.notifier) fixed itself  through another bug fix. So I'll close this.

Ultimately the solution to your issue should probably be scoped providers. I will make scoped providers easier to use

**Closed by rrousselGit** 2021-08-19 21:27 UTC
Labels: question
