### ISSUE TITLE
Add read method to Provider object

### ISSUE THREAD

**Issue by chunlee-thong** [rrousselGit/river_pod#223] opened 2020-11-21 03:00 UTC
the only way we can read provider without listening to it is using `context.read(myProvider)`
As we know that extension method isn't auto complete or suggested by current flutter plugin in both VS code and Android studio, so this lead us to manually import riverpod manually.

### Solution:
I think we should have a method to read it from provider directly.
Example:

final myNotifierProvider = ChangeNotifierProvider((_) {
  return MyNotifier();
});

class MyNotifier extends ChangeNotifier {
  int count;
  // TODO: typical ChangeNotifier logic
}

### read the provider
`myNotifierProvider.read(context)`

**Comment by rrousselGit** [comment] 2020-11-21 04:55
The problem is, if we have `provider.read(context) ` then it wouldn't make sense to have `ref.read(provider)`

We'd want `provider.read(ref)` too, but that is not feasible because the name is taken.

**Comment by rrousselGit** [comment] 2020-11-21 14:22
Closing as I don't think this is feasible without degrading the API.

If you want such function, you can implement it on your own using extensions.

**Closed by rrousselGit** 2020-11-21 14:22 UTC
Labels: enhancement, needs triage
